### ISSUE TITLE
Pug component language prevents new auto a-la-carte from working

### ISSUE THREAD

**Issue by shongololo** [vuetifyjs/vuetify-loader#10]
Use of pug in components seems to prevent the new auto a-la-carte from working as intended.

Here is an example repo: [https://github.com/shongololo/vuetify-a-la-carte](https://github.com/shongololo/vuetify-a-la-carte)

Example errors:

```
[Vue warn]: Unknown custom element: <v-app> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <App> at src/components/App.vue
       <Root>
```

**Comment by KaelWD** [comment]
vuetify-loader has to run *before* pug to be able to inject the imports, and currently it just loads the file separately from disk. If someone with more webpack experience knows how to get the result of the template compilation that'd be great, because I can't figure it out. 

Also pug sucks balls any way so....

**Comment by amritk** [comment]
I have an idea, its probably not as performant, but it should make it work for pug. Will make a pull request later today.

**Comment by amritk** [comment]
@shongololo try loading it like this in your package.json and see if it works:
```
"vuetify-loader": "github:amritk/vuetify-loader",
```

**Comment by shongololo** [comment]
@amritk I can confirm that this now works for the test repo!

Thanks!

**Comment by KaelWD** [comment]
I guess that'll have to do, I was hoping to be able to use something that had already been through vue-loader.

**Comment by amritk** [comment]
Yea that would've been ideal as this isn't very efficient, but it works. I'll make the changes
