### ISSUE TITLE
TypeError: Cannot read property 'match' of undefined in 1.4.0

### ISSUE THREAD

**Issue by nwtgck** [vuetifyjs/vuetify-loader#101]
Hi, developers!

When I updated vuetify-loader from 1.3.1 to 1.4.0, I had the following error by `npm run build`.

> ERROR  TypeError: Cannot read property 'match' of undefined

![image](https://user-images.githubusercontent.com/10933561/69473725-edc02880-0dfa-11ea-92a5-6398829a99ca.png)

## Demo

I made a minimal sample Vue project for this error like the following.

Minimal demo app: <https://github.com/nwtgck/public-code/tree/ba1276f6885a021c17deb296cbd36522704510e2/vuetify-loader-cannot-read-match-of-undefined>

The minimal project was made by `vue create ...` and `vue add vuetify` only, and updated vuetify-loader to 1.4.0. The npm-build works properly in ` vuetify-loader@1.3.1` but doesn't work in ` vuetify-loader@1.3.0` and ` vuetify-loader@1.4.0`.

Maybe related to this comment: <https://github.com/vuetifyjs/vuetify-loader/pull/97#issuecomment-557767269>.

**Comment by nwtgck** [comment]
@jacekkarczmarczyk Could you tell me this was duplicate or solved?

**Comment by jacekkarczmarczyk** [comment]
Workaround (should work, didn't check)
```
// webpack.config.js

const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin')

exports.plugins.push(
  new VuetifyLoaderPlugin({})
)
```

or

```
// vue.config.js

module.exports = {
  chainWebpack: config => config.plugin('VuetifyLoaderPlugin').tap(args => [{}])
}
```

**Comment by Fallpoint** [comment]
This worked for me, thx!

**Comment by jacekkarczmarczyk** [comment]
Thanks for information @Fallpoint
