### ISSUE TITLE
Need option to Handle all vue-loader option

### ISSUE THREAD

**Issue by SmileSmith** [vuetifyjs/vuetify-loader#106]
## Environment
vuetify Version: 2.1.0
vuetify-loader Version: 1.3.0
vue-cli Version: 3.0.3

## Steps to reproduce
this is appear when integrate VuePress in my vuetify project. I found vuetify-component not `inject import` and `register component` by vuetify-loader. reference [https://github.com/vuejs/vuepress/tree/master/packages/%40vuepress/markdown-loader](https://github.com/vuejs/vuepress/tree/master/packages/%40vuepress/markdown-loader)

```javascript
/ * my vuetify project  vue.config.js */

module.exports = {
  transpileDependencies: ['vuetify'],
  chainWebpack: config => {
    const rule = config.module.rule('markdown').test(/\.md$/)
    rule.use('vue-loader').loader('vue-loader');
    rule.use('markdown-loader').loader(require.resolve('@vuepress/markdown-loader'));
  }
}
```

## Expected Behavior
@vuepress/markdown-loader and vuetify component all work

## Actual Behavior
webpack compiler error. `v-app-bar` .etc vuetify component haven't register.

And If covert `.loader('vue-loader');` to `.loader('my-vue-loader');` (or any name else), vuetify-loader plugin work.

Then I found plugin.js only handle **latest** `vue-loader` options. I suggest an option to specific whether to handle all vue-loader option.

```javascript
/* in vuetify-loader/lib/plugin.js 24-26 */

    // find the rule that applies to vue files
    const vueRuleIndex = rules.findIndex(rule => rule.use && rule.use.find(isVueLoader))
    const vueRule = rules[vueRuleIndex]
```

**Comment by bdiz** [comment]
I have the same issue. Using @EqualMa fix resolved the issue for me. Without a full understanding, I do wonder why not always handleAllVueLoaders instead of making it an option. @KaelWD looking forward for the fix to be released.

**Comment by AGDholo** [comment]
I'm using gridsome with vue-cli and vuetify-loader,  
There is a bug: 
```text
You may need an additional loader to handle the result of these loaders. 
Module parse failed: Unexpected token (184:6)
File was processed with these loaders:
 * ./node_modules/vuetify-loader/lib/loader.js
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/vue-loader/lib/index.js
```

It seems that <page-query> block is handled by vuetify. How can I block it?

```html
<page-query>
query {
  posts: allBlog {
    edges {
      node {
        id
        title
      }
    }
  }
}
</page-query>
```
