### ISSUE TITLE
Unknow custom element: <transition>

### ISSUE THREAD

**Issue by Djaler** [vuetifyjs/vuetify-loader#11]
vuetify-loader breaks transitions, if class component was used.
You can see example in my repo https://github.com/Djaler/VuetifyLoaderBugSample/commits/master
![image](https://user-images.githubusercontent.com/7964583/46951917-0d324100-d092-11e8-9b24-87a02b80a52d.png)

**Comment by Djaler** [comment]
@KaelWD thank you! Can you make a new release with this fix?

**Comment by KaelWD** [comment]
It'll have to wait until I get home.

**Comment by Djaler** [comment]
Of course, thanks again

**Comment by Djaler** [comment]
@KaelWD sorry, but looks like problem is not completely solved. More precisely, this is now another problem. Check latest version of my example - https://github.com/Djaler/VuetifyLoaderBugSample/tree/09e7d216b00ca481540e391ea29bb6baa7108c77

**Comment by KaelWD** [comment]
No idea what's causing that, everything's registered fine until `Main` is actually created.

**Comment by Djaler** [comment]
Check latest commit please. If I remove router and use child component directly - it works fine.

**Comment by KaelWD** [comment]
Wow that's super weird. I'll have another poke at it.

**Comment by Djaler** [comment]
@KaelWD I have new failed case :D check latest commits please

**Comment by KaelWD** [comment]
Ok this is getting silly, now only `options` is working instead of `extendOptions`. I'll have to get someone from vue to have a look at this, I've got no idea what's going on.

**Comment by Djaler** [comment]
What if use both `component.exports.extendOptions` and `component.exports.options`?

**Comment by Djaler** [comment]
I changed code of `installComponents` to this:
```
if (typeof component.exports === 'function') {
        component.exports.extendOptions.components = component.exports.extendOptions.components || {}

        for (var i in components) {
            component.exports.extendOptions.components[i] = component.exports.extendOptions.components[i] || components[i]
        }

        component.exports.options.components = component.exports.options.components || {}

        for (var i in components) {
            component.exports.options.components[i] = component.exports.options.components[i] || components[i]
        }
    } else {
        component.options.components = component.options.components || {}

        for (var i in components) {
            component.options.components[i] = component.options.components[i] || components[i]
        }
    }
```
And it looks like all works good.
But this is just proff of concept.

**Comment by KaelWD** [comment]
Thanks I hate it. Pushed up a simplified version, it's terrible but at least it works. 

Release coming soon, thanks for your help troubleshooting.

**Comment by DenisPitcher** [comment]
This change has broken my project.

I have a value returned for component.options but not for component.exports.extendOptions so attempts to set options.component fails as options is not defined.
