### ISSUE TITLE
[Feature Request] support build es5 code

### ISSUE THREAD

**Issue by ac88** [vuetifyjs/vuetify-loader#111]
### Problem to solve
support build es5 code

### Proposed solution
i use vuetify-loader automatically importing all the Vuetify components in vue-cli3

```js
// vue.config.js

const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin')

module.exports = {
  configureWebpack: {
    plugins: [
      new VuetifyLoaderPlugin()
    ],
  },
}
```

after vue-cli-service build,the dist/js code is not es5

eg:VDialog 

```
methods: {
    animateClick() {}
}
```

vuetify has es5 and lib folder,but vuetify-loader only use /lib/ path

https://github.com/vuetifyjs/vuetify-loader/blob/8fb681f4420cab9b8466dd23e0bc6bd06b32874f/lib/matcher/tag.js#L7

https://github.com/vuetifyjs/vuetify-loader/blob/8fb681f4420cab9b8466dd23e0bc6bd06b32874f/lib/matcher/attr.js#L4

i think it maybe have compatibility problem like UC Browser for Android

i have to manually add transpileDependencies parameter in vue.config.js

**Comment by KaelWD** [comment]
> i have to manually add transpileDependencies parameter in vue.config.js

Correct

> vuetify-loader only use /lib/ path

/es5 uses commonjs modules so isn't tree-shakable.
