### ISSUE TITLE
(Vuetify 2.0.2+vue-loader 1.4.3+Jest) Jest unit test cases are failing, Vuetify component registration is failing 

### ISSUE THREAD

**Issue by baluonline** [vuetifyjs/vuetify-loader#115]
Note : Vuetify 1.0.* is working with jest for unit testing
> Package.json has below npms

"vuetify": "^2.0.2",
"jest-vue": "^0.8.2",
  "vuetify-loader": "1.4.3",
  "vue-loader": "^12.2.2",
"babel-core": "^6.26.0",
 "babel-loader": "^7.1.2",

Package.json have below jest configs
 "jest": {
    "moduleFileExtensions": [
      "js",
      "json",
      "vue"
    ],
    "testURL": "http://localhost/",
    "transform": {
      ".*\\.(vue)$": "<rootDir>/node_modules/vue-jest",
      "^.+\\.js$": "babel-jest"
    },
    "setupFiles": [
      "<rootDir>/test/jest-setup.js"
    ],
    "globals": {
      "vue-jest": {
        "tsConfig": {
          "importHelpers": true
        },
        "babelConfig": {
          "presets": [
            [
              "env",
              {
                "useBuiltIns": "entry",
                "shippedProposals": true
              }
            ]
          ],
          "plugins": [
            "syntax-dynamic-import"
          ],
          "env": {
            "test": {
              "plugins": [
                "dynamic-import-node"
              ]
            }
          }
        }
      }
    }
  }

**Issue :** 
Keep getting below warnings for all vuetify components (eg : vcontainer , vrow, vcol, vcard etc)

<console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
    [Vue warn]: Unknown custom element: <v-card-actions> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
    
    found in
    
    ---> <somComponent>
           <Root>
>

**Comment by KaelWD** [comment]
Vuetify-loader has not and will never work with jest. 

https://vuetifyjs.com/en/getting-started/unit-testing#bootstrapping-vuetify

**Comment by baluonline** [comment]
I had followed the same steps for unit testing, It was working fine with vuetify-1.0.* But getting component registration warnings with vuetify-2.0.2.
