### ISSUE TITLE
Progressive Images working on a Vue CLI project

### ISSUE THREAD

**Issue by austinbv** [vuetifyjs/vuetify-loader#116]
We have a VueCLI project with Vuetify loaded via the VueCLI.

We have been trying to configure progressive images using the `vue.config.js` and have seen no effect from any config changes. 

Right now our vue.config.js looks like this:

```js
module.exports = () => {
  chainWebpack: config => {
      config.plugin("VuetifyLoaderPlugin").tap(args => [
        {
          progressiveImages: true
        }
      ]);
    },
  }
}
```

and we have a basic `v-img` like this

```html
     <v-img
        class="video"
        aspect-ratio="0.75"
        alt="book"
        src="~@/assets/images/hero-14.jpg"
        max-width="100%"
      ></v-img>
```

I would expect to see in the `vue-devtools` the `lazy-src` for the v-img to have the thumbnail in the `lazy-src`.

I do have ImageMagick installed

```
→ which magick
/usr/local/bin/magick
```

Here is my vuetify loader version
```
 → yarn why vuetify-loader
yarn why v1.22.0
[1/4] 🤔  Why do we have the module "vuetify-loader"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "vuetify-loader@1.4.3"
```

**Comment by KaelWD** [comment]
> the thumbnail in the `lazy-src`

The `src` prop is an object when using `progressiveImages`, it doesn't use `lazy-src`
