### ISSUE TITLE
v-img not working for UC mobile browser. some mobile browser may filter ad.png image.

### ISSUE THREAD

**Issue by jiaosw** [vuetifyjs/vuetify-loader#117]
v-img not working for UC mobile browser. some mobile browser may filter ad.png image.
`

            <v-col cols="12">
                //working
                <img alt="Vue logo" :src="require('@/assets/logo.png')">
                //not working
                <v-img :src="require('@/assets/logo.png')"
                       class="my-3"
                       contain
                       height="200"
                />

`

**Comment by jiaosw** [comment]
<v-col cols="12">
                //working
                <img alt="Vue logo" :src="require('@/assets/logo.png')">
                //not working
                <v-img :src="require('@/assets/logo.png')"
                       class="my-3"
                       contain
                       height="200"
                />
            </v-col>

**Comment by jiaosw** [comment]
[<v-col cols="12">
                //working
                <img alt="Vue logo" :src="require('@/assets/logo.png')">
                //not working
                <v-img :src="require('@/assets/logo.png')"
                       class="my-3"
                       contain
                       height="200"
                />
            </v-col>](url)

**Comment by jiaosw** [comment]
/***/ "./src/assets/logo.png":
/*!*****************************!*\
  !*** ./src/assets/logo.png ***!
  \*****************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

eval("module.exports =3D __webpack_require__.p + \"img/logo.82b9c7a5.png\";=
//# sourceURL=3D[module]\n//# sourceMappingURL=3Ddata:application/json;char=
set=3Dutf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiLi9zcmMvYXNzZXRzL2xvZ28ucG5n=
LmpzIiwic291cmNlcyI6WyJ3ZWJwYWNrOi8vLy4vc3JjL2Fzc2V0cy9sb2dvLnBuZz8xOTAwIl0=
sInNvdXJjZXNDb250ZW50IjpbIm1vZHVsZS5leHBvcnRzID0gX193ZWJwYWNrX3B1YmxpY19wYX=
RoX18gKyBcImltZy9sb2dvLjgyYjljN2E1LnBuZ1wiOyJdLCJtYXBwaW5ncyI6IkFBQUEiLCJzb=
3VyY2VSb290IjoiIn0=3D\n//# sourceURL=3Dwebpack-internal:///./src/assets/log=
o.png\n");

**Comment by KaelWD** [comment]
This is the wrong repository for this issue, and vuetify doesn't support UC browser.
