### ISSUE TITLE
Vuetify-loader doesn't support sass-loader 8.x

### ISSUE THREAD

**Issue by joelpro2** [vuetifyjs/vuetify-loader#121]
Vuetify supports  sass-loader 8.x as described in [documentation](https://vuetifyjs.com/en/customization/sass-variables/#webpack-install).

Meanwhile vuetify-loader is still behind, and try's to write a data property in sass-loader option which is one breaking change from 7.x

Outputing the webpack.config.js file we see that a data property is being generated by vuetify-loader.

```javascript
use: [
  {
    loader: 'sass-loader',
    options: {
      data: '@import \'~vuetify/src/styles/styles.sass\''
    }
  }
]
```

```javascript
"dependencies": {
  "vuetify": "^2.2.18"
},
"devDependencies": {
  "vuetify-loader": "^1.4.3"
}
```

**Comment by MajesticPotatoe** [comment]
After looking this over, `vue-cli-plugin-vuetify` is responsible for the sass-loader configuration which is setup for 8.0.
Check to make sure you have the latest installed. (I messaged you in discord)
