### ISSUE TITLE
how can make it support compatible ie11?

### ISSUE THREAD

**Issue by freezyh** [vuetifyjs/vuetify-loader#122]
if vuetify A-la-carte, but it can't use in ie11, how to do it

**Comment by jacekkarczmarczyk** [comment]
Add transpileDependencies in your vue.config.js 
https://vuetifyjs.com/en/getting-started/browser-support/#ie-11-amp-safari-9-support

**Comment by freezyh** [comment]
I use @vue/cli 4.2.3, It can't add  babel-polyfill, because it include core-js, if add babel-polyfill , it will error, you can try it.

**Comment by freezyh** [comment]
> Add transpileDependencies in your vue.config.js
> https://vuetifyjs.com/en/getting-started/browser-support/#ie-11-amp-safari-9-support

I use @vue/cli 4.2.3, It can't add babel-polyfill, because it include core-js, if add babel-polyfill , it will error, you can try it.
