### ISSUE TITLE
[Bug Report] Vuetify can't use import it by CDN and treeshaking at the same time to support IE11 or IE10

### ISSUE THREAD

**Issue by freezyh** [vuetifyjs/vuetify-loader#123]
### Environment

**Browsers:** Chrome 78.0.3904.97
**OS:** Windows

### Steps to reproduce
Now I want to use Vuetify import by CDN and treeshaking to support IE11 or IE10.
// vue.config.js
const isProduction = process.env.NODE_ENV === 'production'

const cdn = {
  css: [
    'https://cdn.bootcss.com/vuetify/2.2.15/vuetify.min.css',
    'https://cdn.bootcss.com/element-ui/2.13.0/theme-chalk/index.css'
  ],
  js: [
    'https://cdn.bootcss.com/vue/2.6.11/vue.min.js',
    'https://cdn.bootcss.com/vuetify/2.2.15/vuetify.min.js',
  ]
}
module.exports = {
  publicPath: './',
  productionSourceMap: !isProduction,
  chainWebpack: config => {
    if (isProduction) {
        config.plugin('html')
            .tap(args => {
                args[0].cdn = cdn;
                return args;
            });
    }
  },
  configureWebpack: config => {
    if (isProduction) {
        config.externals = {
          'vue': 'Vue',
          'vuetify': 'Vuetify',
          'element-ui': 'ELEMENT'
        }
    }
  },
  "transpileDependencies": [
    "element-ui",
    "vuetify"
  ]
}
Now I want to use Vuetify import by CDN and treeshaking to support IE11 or IE10.
// vue.config.js
const isProduction = process.env.NODE_ENV === 'production'

const cdn = {
  css: [
    'https://cdn.bootcss.com/vuetify/2.2.15/vuetify.min.css',
    'https://cdn.bootcss.com/element-ui/2.13.0/theme-chalk/index.css'
  ],
  js: [
    'https://cdn.bootcss.com/vue/2.6.11/vue.min.js',
    'https://cdn.bootcss.com/vuetify/2.2.15/vuetify.min.js',
  ]
}
module.exports = {
  publicPath: './',
  productionSourceMap: !isProduction,
  chainWebpack: config => {
    if (isProduction) {
        config.plugin('html')
            .tap(args => {
                args[0].cdn = cdn;
                return args;
            });
    }
  },
  configureWebpack: config => {
    if (isProduction) {
        config.externals = {
          'vue': 'Vue',
          'vuetify': 'Vuetify',
          'element-ui': 'ELEMENT'
        }
    }
  },
  "transpileDependencies": [
    "element-ui",
    "vuetify"
  ]
}

// index.html
<!DOCTYPE html>
<html lang="zh-Hans">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="icon" href="<%= BASE_URL %>favicon.ico">
    <title><%= htmlWebpackPlugin.options.title %></title>
    
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@mdi/font@latest/css/materialdesignicons.min.css">
    <% for (var i in
    htmlWebpackPlugin.options.cdn&&htmlWebpackPlugin.options.cdn.css) { %>
    <link href="<%= htmlWebpackPlugin.options.cdn.css[i] %>" rel="preload" as="style" />
    <link href="<%= htmlWebpackPlugin.options.cdn.css[i] %>" rel="stylesheet" />
    <% } %>
    <% for (var i in htmlWebpackPlugin.options.cdn && htmlWebpackPlugin.options.cdn.js) { %>
      <link href="<%= htmlWebpackPlugin.options.cdn.js[i] %>" rel="preload" as="script">
    <% } %>
  </head>
  <body>
    <noscript>
      <strong>We're sorry but <%= htmlWebpackPlugin.options.title %> doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
    </noscript>
    <div id="app"></div>
    
    <% for (var i in
    htmlWebpackPlugin.options.cdn&&htmlWebpackPlugin.options.cdn.js) { %>
    <script src="<%= htmlWebpackPlugin.options.cdn.js[i] %>"></script>
    <% } %>
   
  </body>
</html>

//vuetify.js
import Vue from 'vue'
import Vuetify from 'vuetify'

Vue.use(Vuetify)

const opts = {}

export default new Vuetify(opts)
//Login.vue
<template>
  <div>
    <v-app>
        <v-form v-model="valid" class="my-form">
          <div>
            <v-text-field
              v-model="firstname"
              :rules="nameRules"
              label="订单号"
              required
            ></v-text-field>
          </div>
          <div>
            <v-text-field
              v-model="lastname"
              :rules="nameRules"
              :counter="10"
              label="Last name"
              required
            ></v-text-field>
          </div>
          <div>
            <v-text-field
              v-model="email"
              :rules="emailRules"
              label="E-mail"
              required
            ></v-text-field>
          </div>
        </v-form>
  </v-app>
  </div>
</template>

<script>
import { VApp, VForm, VTextField } from 'vuetify/lib'
export default {
  name: 'Login',
  components: {
    VApp, VForm, VTextField
  },
  data () {
    return {
      valid: false,
      firstname: '',
      lastname: '',
      nameRules: [
        v => !!v || '必须输入',
        v => v.length <= 10 || 'Name must be less than 10 characters'
      ],
      email: '',
      emailRules: [
        v => !!v || 'E-mail is required',
        v => /.+@.+/.test(v) || 'E-mail must be valid'
      ]
    }
  },
  methods: {
  }
}
</script>
<style lang="scss">
  .my-form .v-text-field__slot {
    border: 1px solid;
    border-radius: 4px;
    padding: 0 10px;
  }
  .my-form .v-input__slot::before {
    display: none;
  }
  .my-form .v-input__slot::after {
    display: none;
  }
  .my-form .theme--light {
    left: 10px !important;
    padding: 0 4px;
    background-color: #ffffff;
  }
  .my-form .v-label--active.theme--light {
    top: 10px !important;
  }
</style>

### Expected Behavior
build the project

### Actual Behavior
After build project, the packsize is smaller really, and it can use in popular browser, but it can't support in IE11 or IE10, it tip "Object does not support 'startswith' property or method" and "
'vuetify' is not defined"

### Reproduction Link
<a href="" target="_blank"></a>

**Comment by KaelWD** [comment]
Your formatting is a mess. If you want to support IE then use babel. 

https://vuetifyjs.com/en/getting-started/browser-support/
