### ISSUE TITLE
How to manually import base styles

### ISSUE THREAD

**Issue by glen-84** [vuetifyjs/vuetify-loader#128]
When using vuetify-loader, you must import Vuetify from `vuetify/lib`, which then automatically brings in the base styles.

Because of this, in order to set Sass variables, you have to use a hack by prepending an import to all Sass files, like this:

```js
prependData: (loaderContext) => {
    if (loaderContext.resourcePath.endsWith(".sass")) {
        return "@import 'src/styles/variables.scss'";
    } else {
        return "@import 'src/styles/variables.scss';";
    }
}
```

This is ugly and according to the webpack documentation, it could lead to issues with source mappings.

I would prefer to manually import the base styles after importing variables – is that somehow possible?

**Comment by KaelWD** [comment]
No, component styles are all brought in separately so you can't just include variables once.

**Comment by glen-84** [comment]
That's unfortunate. Perhaps using CSS custom properties for everything (including fonts, etc.) would make things easier to customize?

**Comment by KaelWD** [comment]
It's being considered for v3

**Comment by glen-84** [comment]
Okay, thanks Kael.
