### ISSUE TITLE
How to control where vuetify style tags are inserted when using webpack

### ISSUE THREAD

**Issue by flyingL123** [vuetifyjs/vuetify-loader#129]
Is there any way to control where the vuetify style tags get inserted into the DOM? I thought I had it figured out when I discovered the [`insert` option on the `style-loader`](https://webpack.js.org/loaders/style-loader/#insert), but this doesn't seem to have any effect.

Is vue-loader doing the style insertion? Or is it the style-loader? I've been trying to figure this out for a few days and at this point I'm not even sure where to look. It's difficult to even tell which loader/library is doing it.

Are you able to provide any guidance on this? I am currently implementing vuetify into an existing theme, and vuetify keeps overriding all of my existing styles since they have the same specificity and vuetify is being inserted last.

------

UPDATE - I am realizing now that I was actually attempting to use the `insert` option on the `vue-style-loader`, not the `style-loader`. It appears the `insert` option is removed from the `vue-style-loader`. So perhaps if I use the base style-loader instead, then the `insert` option will change where vuetify styles get inserted?

**Comment by KaelWD** [comment]
You seem to have found the answer to this yourself, vuetify-loader only adds `import` statements and does not control style loading in any way.
