### ISSUE TITLE
[Bug Report] Vuetify-loader breaks with ElectronJS v9 when 'remote' module is loaded

### ISSUE THREAD

**Issue by tommybravo** [vuetifyjs/vuetify-loader#134]
### Environment

**Browsers:** Chrome 83.0.4103.97
**OS:** Windows 10

### Steps to reproduce
1. Create a vue project with vue-cli
2. Add vuetify
3. Add electron-builder
4. In background.js, set enableRemoteModule: true for the main BrowserWindow
5. In the App.vue, add const {app} = require('electron').remote

### Expected Behavior
{app} functions can be accessed from App.vue

### Actual Behavior
It appears that vue-loader tries to use the 'fs.existsSync' that is not directly available in Electron v9.

> Uncaught TypeError: fs.existsSync is not a function
>    at getElectronPath (index.js?bdb9:7)
>    at eval (index.js?bdb9:18)
>   at Object../node_modules/electron/index.js (chunk-vendors.js:1289)
>    at __webpack_require__ (app.js:854)
>    at fn (app.js:151)
>    at eval (App.vue?234e:24)
>    at Module../node_modules/vuetify-loader/lib/loader.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/App.vue?vue&type=script&lang=js& (app.js:1043)
>    at __webpack_require__ (app.js:854)
>    at fn (app.js:151)
>    at eval (App.vue?c488:1)

### Reproduction Link
<a href="" target="_blank"></a>

### Other comments
I'm not sure if that is attributable to vue-loader, but the above error from console says that vuetify-loader plays a part in the error. Details on the new behavior of Electron 9: [API Changed: require()ing node builtins in sandboxed renderers no longer implicitly loads the remote version](https://www.electronjs.org/docs/breaking-changes#api-changed-requireing-node-builtins-in-sandboxed-renderers-no-longer-implicitly-loads-the-remote-version)

**Comment by KaelWD** [comment]
I can't find `existsSync` used in either vue-loader or vuetify-loader. Even if it was that shouldn't affect electron at runtime, loaders are executed by webpack during build.   
That call actually appears to be in electron's code: https://github.com/electron/electron/blob/6c998aa4f2ee7d998a0fbd8613b9d62ccf6d3492/npm/index.js#L1-L7
