### ISSUE TITLE
[Bug Report] Install Template A-la-carte error when follow the instruction Document

### ISSUE THREAD

**Issue by lekhang2512** [vuetifyjs/vuetify-loader#135]
### Environment
**Vuetify Version:** 2.3.1
**Vue Version:** 3.0.0-alpha.13
**Browsers:** Chrome 83.0.4103.116
**OS:** Linux x86_64

### Steps to reproduce
no

### Expected Behavior
no

### Actual Behavior
no

### Reproduction Link
<a href="" target="_blank"></a>

**Comment by KaelWD** [comment]
Vuetify does not work with Vue 3 yet.
