### ISSUE TITLE
[Bug Report] Unable to override Vuetify Sass Variables

### ISSUE THREAD

**Issue by ItzhakS** [vuetifyjs/vuetify-loader#137]
### Environment

**Browsers:** Chrome 83.0.4103.106
**OS:** Windows 10

### Steps to reproduce
* Create vue project.
* Install Vuetify.
* Create local _variables.scss file in vue src/styles folder.
* Updated vue.config.js
* npm run serve

### Expected Behavior
Vuetify sass variables will be overwritten by local values.

### Actual Behavior
Sass-Loader Error -

 error  in ./node_modules/vue-interface/src/Components/ActivityIndicator/Types/Spinner.vue?vue&type=style&index=0&lang=scss&

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: $color: ("base": #2196F3, "lighten-5": #E3F2FD, "lighten-4": #BBDEFB, "lighten-3": #90CAF9, "lighten-2": #64B5F6, "lighten-1": #42A5F5, "darken-1": #1E88E5, "darken-2": #1976D2, "darken-3": #1565C0, "darken-4": #0D47A1, "accent-1": #82B1FF, "accent-2": #448AFF, "accent-3": #2979FF, "accent-4": #2962FF) is not a color.
    ╷
183 │ $link-hover-color:                        darken($link-color, 15%) !default;
    │                                           ^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules\bootstrap\scss\_variables.scss 183:43  @import
  C:\Users\Ishachnovitz\Tribemap\tribemap-vue-frontend\node_modules\vue-interface\src\Components\ActivityIndicator\Types\Spinner.vue 23:9                                          root stylesheet

### Reproduction Link
<a href="" target="_blank"></a>

### Other comments

# The files in questions:
## vue.config.js
```
css: {
        loaderOptions: {
            sass:{
                prependData: "@import '~@/styles/_variables.sass'"

            },
            scss: {
                prependData: "@import '~@/styles/_variables.scss';"

            }
        }
    } 
```

## _variables.scss
```
$body-font-family: cursive !default;
$border-radius-root: 6px;
$font-size-root: 20px;

@import '~vuetify/src/styles/styles.sass';
@import '~vuetify/src/styles/settings/_variables.scss'; 
```
 
"dependencies": {

    "vue": "^2.6.11",
    "vuetify": "^2.3.2",
  },
  "devDependencies": {
    "@vue/cli-service": "^4.4.6",
    "node-sass": "^4.14.1",
    "sass": "^1.26.9",
    "sass-loader": "^8.0.2",
    "style-loader": "^1.2.1",
    "stylus": "^0.54.7",
    "stylus-loader": "^3.0.1",
    "vuetify-loader": "^1.5.0"

**Comment by KaelWD** [comment]
- This is not related to vuetify-loader
- The error is coming from the `vue-interface` package, not vuetify
- You shouldn't import `styles.sass` in the variables file
- You don't need to import `_variables.scss` in the variables file
- You have both `sass` and `node-sass` installed

**Comment by ItzhakS** [comment]
@KaelWD Then I am at a loss. All references I have found (in other Github issues and SO) point to importing the `styles.sass` in the variables file. If I remove the import then the project compiles however the Vuetify sass variables are not overridden with the variables in my file.

Is there more specific direction you can offer?

**Comment by KaelWD** [comment]
- You shouldn't use `!default` there
- You have two different _variables files specified in vue.config.js, the only difference between those lines should be the semicolon. 

> All references I have found

The official example doesn't: https://vuetifyjs.com/en/customization/sass-variables/#example-variable-file

**Comment by Maxim-Mazurok** [comment]
I was trying to do this:
```
module.exports = {
  //..
  configureWebpack: {
    //...
    module: {
      rules: [
        {
          test: /\.s[ac]ss$/i,
          use: [
            "vue-style-loader",
            "css-loader",
            {
              loader: "sass-loader",
              options: {
                additionalData: "@import '@/styles/_variables.scss';",
              },
            },
          ],
        },
      ],
    },
  },
};
```
This worked:
```
module.exports = {
  transpileDependencies: ["vuetify"],
  css: {
    loaderOptions: {
      sass: {
        implementation: require("sass"),
        additionalData: "@import '@/styles/_variables.scss'",
      },
      scss: {
        additionalData: "@import '@/styles/_variables.scss';",
      },
    },
  },
  //...
};
```
