### ISSUE TITLE
Export VuetifyLoaderPlugin from index.js

### ISSUE THREAD

**Issue by glen-84** [vuetifyjs/vuetify-loader#138]
Would it make sense to export `VuetifyLoaderPlugin` from `index.js`, as [vue-loader](https://github.com/vuejs/vue-loader/blob/d5f7e16570c83b74019d435b4b47a5a21431699e/lib/index.js#L197) does?

Doing so would allow:

```js
const {VuetifyLoaderPlugin} = require("vuetify-loader");
```

... instead of:

```js
const VuetifyLoaderPlugin = require("vuetify-loader/lib/plugin");
```

**Comment by KaelWD** [comment]
Yeah probably.
