### ISSUE TITLE
[Vuetify] Image load failed

### ISSUE THREAD

**Issue by thelosttimes** [vuetifyjs/vuetify-loader#141]
[Vuetify] Image load failed

src: data:image/jpeg;base64,bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICJpbWcvbG9naW4uZDZkM2JiMDkuanBnIjs=

found in

---> <VImg>
       <VContent>
         <PagesCoreView> at src/views/pages/components/core/View.vue
           <VApp>
             <PagesIndex> at src/views/pages/Index.vue
               <App> at src/App.vue
                 <Root>

**Comment by KaelWD** [comment]
This Issue is being closed due to inactivity.

If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com/).
