### ISSUE TITLE
SASS variables.scss

### ISSUE THREAD

**Issue by stephenjason89** [vuetifyjs/vuetify-loader#146]
I have a variables.scss in my resources/sass/variables.scss
it contains this simple style

>
@import "~vuetify/src/styles/styles.sass";
$btn-sizes: (
    "default": 500,
    "large": 200
);

my webpack mix is 

>
    .extend('vuetify', new class {
        webpackConfig(config) {
            config.plugins.push(new VuetifyLoaderPlugin)
        }
    })
    .vuetify()
>

and on my template a simple
`<v-btn color="primary">Primary</v-btn>`

how can I make it work? 
I'm trying to use this to make themes for my app.

Thank you!

**Comment by KaelWD** [comment]
Vuetify-loader doesn't affect sass. Try using https://laravel-mix.com/extensions/vuetifyjs

**Comment by stephenjason89** [comment]
Thanks
