### ISSUE TITLE
[Question] Is Vuetify working/stable with Vue 3 RC (3.0.0-rc.8)

### ISSUE THREAD

**Issue by larsmars** [vuetifyjs/vuetify-loader#150]
Is Vuetify working/stable with Vue 3 RC (3.0.0-rc.8)?

The question is if it is **stable or even working with Vue 3 RC (3.0.0-rc.8)**

I know there is a v3.0 Release on the Vuetify roadmap for Q3/Q4.

Considering starting a new project with Vue 3 and Vuetify.

**Comment by jacekkarczmarczyk** [comment]
No, you need to wait for Vuetify 3.0
