### ISSUE TITLE
[Bug Report] Progressive Images not working for webp

### ISSUE THREAD

**Issue by dvdmlln** [vuetifyjs/vuetify-loader#152]
### Environment

**Vuetify Version:** 2.3.10
**Vue Version:** 2.6.12
### Steps to reproduce

    1. Add progressiveImages to the plugin options
    2. Create v-img with webp image as source

### Expected Behavior

Low-res placeholders for the webp source are generated
### Actual Behavior

Same behavious as progressiveImages set to false

**Comment by Barbapapazes** [comment]
hello, I'm working on a pull request to solve this issue

**Comment by KaelWD** [comment]
This was added in v1.7.0 with 4de3c946f329bcce3548a0aa753b34672818bdc0
