### ISSUE TITLE
Adding a markdown config rule seems to break VuetifyLoader

### ISSUE THREAD

**Issue by garyo** [vuetifyjs/vuetify-loader#154]
I'm trying to use vmark-loader to load Markdown as Vue components. I add this to my `configureWebpack` in `vue.config.js`:
```js
    module: {
      rules: [
        {
          test: /\.md$/,
          use: [
            {loader: 'vue-loader'},
            {loader: 'vmark-loader'}
          ]
        }
      ]
    },
```
but when I do that, I get many errors about "unknown custom element <v-spacer>" and so on, same as if I didn't use VuetifyLoaderPlugin at all. If I remove the `vue-loader` line above, then my app works again, except my `Foo.md` component doesn't load because it needs to be processed by `vue-loader`.

**Comment by garyo** [comment]
I was using an older version of vuetify-loader, it seems. Now when I upgrade to 1.6, it doesn't fail anymore. I do still get an error where it says it cannot find my `.md` module but vuetify-loader doesn't seem to be a problem anymore.

**Comment by ktran6086** [comment]
Thank you, this saved me hours and days trying to figure out why the app was breaking from that md vue.config.js change!
