### ISSUE TITLE
[Bug Report] Insertion of unnecessary host and port in v-img

### ISSUE THREAD

**Issue by yerzhant** [vuetifyjs/vuetify-loader#155]
### Environment

**Vue**: 2.6.11
**Vuetify:** 2.3.1
**Browsers:** Chrome 85.0.4183.83
**OS:** Linux x86_64

### Steps to reproduce
Insert a v-img tag:
`<v-img src="./assets/logo.png"></v-img>`

### Expected Behavior
```
<div class="v-image__image v-image__image--contain" style="background-image: url('/img/logo.47217774.png'); background-position: center center;"></div>
```

### Actual Behavior
```
<div class="v-image__image v-image__image--contain" style="background-image: url('https://onlinebus.kz/img/logo.47217774.png'); background-position: center center;"></div>
```

The issue arises when prerendering is used ([prerender-spa-plugin](https://www.npmjs.com/package/prerender-spa-plugin)). If you look at [this](https://onlinebus.kz/) page you'll find this:
```
...
<div class="v-image__image v-image__image--contain" style="background-image: url('http://localhost:8000/img/logo.47217774.png'); background-position: center center;"></div>
...
```

If the loader wouldn't add unnecessary host and port, I guess it'll resolve the issue.

### Reproduction Link
[OnlineBus.kz](https://onlinebus.kz/)

**Comment by KaelWD** [comment]
That's based on your webpack config's `output.publicPath`

**Comment by yerzhant** [comment]
But I haven't set publicPath. In my vue.config.js I have this:
```
...
module.exports = {
  productionSourceMap: false,
  configureWebpack: {
    performance: {
      maxEntrypointSize: 1200 * 1024,
      maxAssetSize: 700 * 1024
    },
    plugins: [new CompressionPlugin()]
  },
...
if (process.env.NODE_ENV === 'production') {
  module.exports.configureWebpack.plugins.push(
    new PrerenderSPAPlugin({
      staticDir: path.join(__dirname, 'dist'),
      routes: ['/', '/contacts']
    })
  )
}
```

Beforehand I tested by a simple img: `<img src="./assets/logo.png"></img>`
In resulting index.html it was without host and port.

**Comment by KaelWD** [comment]
https://github.com/chrisvfritz/prerender-spa-plugin/issues/61

**Comment by yerzhant** [comment]
@KaelWD Thanks a lot for your replies.

I've tried [vue-cli-plugin-prerender-spa](https://www.npmjs.com/package/vue-cli-plugin-prerender-spa). But it didn't work out.

What do you recommend then?
