### ISSUE TITLE
`vuetify-loader` is no longer compatible with `sass-loader`

### ISSUE THREAD

**Issue by Byloth** [vuetifyjs/vuetify-loader#156]
I'm experiencing this error while building a project using both Vuetify and SASS...

```
 ERROR  in ./layouts/error.vue?vue&type=style&index=0&id=d5ea9138&lang=scss&scoped=true&                                                                                                                                                           friendly-errors 18:31:29

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):                                                                                                                                                                                 friendly-errors 18:31:29
ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'prependData'. These properties are valid:
   object { implementation?, sassOptions?, additionalData?, sourceMap?, webpackImporter? }
    at validate (/path/to/project/node_modules/schema-utils/dist/validate.js:98:11)
    at Object.loader (/path/to/project/node_modules/sass-loader/dist/index.js:30:28)
```

---

Recently, the `sass-loader` has been changed and now the `options` structure is different.  
`vuetify-loader` is no longer compatible with `sass-loader`.

I think the problem may be here:
https://github.com/vuetifyjs/vuetify-loader/blob/edfa283784e26f033d818fb5e5c268bf07abe950/dev/webpack.config.js#L12

**Comment by Byloth** [comment]
My bad...  
I just tested this on a "clean" Vue.js + Vuetify.js project without Nuxt.js and it works great!

So, I think, the problem is related to Nuxt.js!

I'll close this issue.  
Sorry again and thanks for your time.

---

More info here: https://github.com/nuxt-community/vuetify-module/issues/386

**Comment by g0shed** [comment]
the problem is not in a clean installation, but rather if you have sass-loader installed then it all goes downhill...

**Comment by taryodor** [comment]
I have this issue with latest Vue + Vuetify + sass-loader 10.2.1 without nuxt.
