### ISSUE TITLE
Does not work with sass-loader 10

### ISSUE THREAD

**Issue by some-user123** [vuetifyjs/vuetify-loader#164]
I'm experiencing this error:
```
Syntax Error: ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'prependData'. These properties are valid:
   object { implementation?, sassOptions?, additionalData?, sourceMap?, webpackImporter? }
```

after upgrading from sass-loader 8 to 10. `prependData` has been renamed to `additionalData`.

Steps to reproduce:
- `vue create ...`
- `vue add vuetify`
- `vue add vuetify-preset-basil`
- Upgrade `sass-loader` from 8 to 10
- `npm run serve`

```json
// Package.json
{
  "name": "...",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build"
  },
  "dependencies": {
    "vue": "^2.6.11",
    "vuetify": "^2.2.11"
  },
  "devDependencies": {
    "@vue/cli-service": "~4.5.0",
    "sass": "^1.26.5",
    "sass-loader": "^10.1.0",
    "vue-cli-plugin-vuetify": "~2.0.9",
    "vue-cli-plugin-vuetify-preset-basil": "~1.0.4",
    "vue-template-compiler": "^2.6.11",
    "vuetify-loader": "^1.3.0"
  }
}
```

**Comment by KaelWD** [comment]
Vuetify-loader does not modify sass-loader options, check your config or vue-cli-plugin-vuetify version.

**Comment by tfabritius** [comment]
Thanks for your comment.
vue-cli-plugin-vuetify is 2.0.9 which is up-to-date to my understanding.

What config are you referring to? I didn't configure anything bit only used above commands.

**Comment by some-user123** [comment]
Thanks for your comment, @KaelWD. Not sure, I fully understand it, though.

`vue-cli-plugin-vuetify` is at version 2.0.9, which is up-to-date to my understanding.
What config are you referring to? I did not change any configuration, I just executed the above commands.
