### ISSUE TITLE
[Bug Report] vuetify-loader extract css file path is "/js/app.css"

### ISSUE THREAD

**Issue by uax** [vuetifyjs/vuetify-loader#172]
### Environment
**Vuetify Version:** 2.4.7
**Vue Version:** 2.6.11
**Browsers:** Chrome 89.0.4389.90
**OS:** Mac OS 10.15.7

### Steps to reproduce
laravel-mix webpack.mix.js:

```const mix = require('laravel-mix');
const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin')

mix.webpackConfig({
    plugins: [
        new VuetifyLoaderPlugin({
            match(originalTag, { kebabTag, camelTag, path, component }) {
                if (kebabTag.startsWith('core-')) {
                    return [camelTag, `import ${camelTag} from '@/components/core/${camelTag.substring(4)}.vue'`]
                }
            }
        })
    ],
});

mix.js('resources/js/app.js', 'public/js')
    .postCss('resources/css/app.css', 'public/css', [])
    .vue({ extractStyles: true });

if (mix.inProduction()) {
    mix.version();
}

```
vuetify.js:
```
import Vue from 'vue'
import Vuetify from 'vuetify/lib'

Vue.use(Vuetify)

const opts = {}

export default new Vuetify(opts)
```

npm run watch result:

│                                                /js/app.css │ 571 KiB  │
│                                                 /js/app.js │ 2.43 MiB │
│                                                css/app.css │ 57.6 KiB │

why extract css file path is "/js/app.css"?
### Reproduction Link
<a href="" target="_blank"></a>

**Comment by KaelWD** [comment]
Vuetify-loader doesn't extract css, that's handled by your build configuration (laravel mix).
