### ISSUE TITLE
@vuetify/loader-shared does not include runtime.js

### ISSUE THREAD

**Issue by AllanChain** [vuetifyjs/vuetify-loader#194]
I am trying out `vuetify@3.0.0-alpha.11` with vite and having `failed to resolve import "@vuetify/loader-shared/runtime" from "src\App.vue"` error.

Lines injected into `App.vue`:
```js
/* Vuetify */
import { installAssets } from "@vuetify/loader-shared/runtime"
```
I think the cause is that `runtime.js` is not included in `package.json` `files`:

https://github.com/vuetifyjs/vuetify-loader/blob/7a6b8266034cfcc5187802dfde3fc49ebc7735f6/packages/shared/package.json#L23-L25

**Comment by KaelWD** [comment]
Fixed in alpha 2
