### ISSUE TITLE
[Bug Report] vite plugin - missing vuetify components when autoImport is false

### ISSUE THREAD

**Issue by lukeromanowicz** [vuetifyjs/vuetify-loader#195]
When running vite plugin with `vuetify({ styles: 'expose', autoImport: false }),`

Importing components this way:
```
  import { VApp, VMain, VAppBar, VImg, VRow, VCol, VContainer } from 'vuetify';
```
Ends up with browser error:
```
Uncaught SyntaxError: The requested module '/node_modules/.vite/vuetify.js?v=7bedb03f' does not provide an export named 'VApp'
```

While importing from `vuetify/dist` produces following error:
```
11:29:22 AM [vite] Internal server error: Failed to resolve import "vuetify/dist" from "src/App.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/lromanowicz/projects/frontend/src/App.vue
  1  |  import { defineComponent } from "vue";
  2  |  import { VApp, VMain, VAppBar, VImg, VRow, VCol, VContainer } from "vuetify/dist";
     |                                                                      ^
  3  |  import { useAuth, LOGOUT_URL } from "./composables/useAuth";
  4  |  import Icon from "./components/atoms/Icon.vue";
      at formatError (/home/lromanowicz/projects/frontend/node_modules/vite/dist/node/chunks/dep-0ed4fbc0.js:44595:46)
```

Plugin 1.0.0-alpha.2
Vuetify 3.0.0-alpha.11
Vite 2.3.8

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/pull/14099

Components are imported from `'vuetify/components'` now.

**Comment by lukeromanowicz** [comment]
@KaelWD components doesn't work either.
IDE can't find it:
![image](https://user-images.githubusercontent.com/46789227/131480220-fa5dbeb1-693b-40a6-b074-feb6933cb3f2.png)

It gets built correctly but produces a following error in the browser:
```
Uncaught SyntaxError: The requested module '/node_modules/vue/dist/vue.runtime.esm-bundler.js' does not provide an export named 'effectScope'
```

**Comment by KaelWD** [comment]
https://youtrack.jetbrains.com/issue/WEB-40509

Weird that you're getting that in a typescript file though, I only got it with js. What version of webstorm is that?

> does not provide an export named 'effectScope'

You need to update Vue

**Comment by lukeromanowicz** [comment]
>What version of webstorm is that?
phpstorm 2021.2

> does not provide an export named 'effectScope'
oh, right! Thank you!

**Comment by KaelWD** [comment]
> Similar thing happens to @use in styles

This happens for me even with a real path like `vuetify/styles/main.sass`

**Comment by lukeromanowicz** [comment]
@KaelWD if the path was 'vuetify/lib/styles/main.scss
1. right click on vuetify in your node_modules
2. select "configure project directories"
3. mark node_modules directory as 'resource root' in addition to source root that most likely it already is.

After that, `@use 'vuetify/lib/styles/main.sass';` should work.

Unfortunately, Jetbrains IDE doesn't seem to recognize aliases from package.json files

**Comment by KaelWD** [comment]
> `@use 'vuetify/lib/styles/main.sass';` should work

Keep in mind that this currently will not be picked up by the vite plugin, so customisations to any variables used in components won't be applied.
