### ISSUE TITLE
Alpha version released as @latest

### ISSUE THREAD

**Issue by Tofandel** [vuetifyjs/vuetify-loader#200]
Running `npm install vuetify-loader` will now install the alpha version, which doesn't seem to have a corresponding version for `vue-cli-plugin-vuetify`

Which effectively will result in the following error
```
 ERROR  Error: Cannot find module 'vuetify-loader/lib/plugin'
        Require stack:
        - node_modules/vue-cli-plugin-vuetify/index.js
        - node_modules/@vue/cli-service/lib/Service.js
        - node_modules/@vue/cli-service/bin/vue-cli-service.js
```

It seems the alpha version was released by mistake on the `@latest` tag instead of the `@next`

**Comment by KaelWD** [comment]
Should be fixed now. I did publish with `--pre-dist-tag next` so not sure why that didn't take.
