### ISSUE TITLE
Exclude Vuetify styles

### ISSUE THREAD

**Issue by yarkovaleksei** [vuetifyjs/vuetify-loader#201]
Hey!
How can I not include Vuetify styles? I don't need them in the build file, because I have my own custom file with styles.
Now I have to cut them from the file after assembly and I have to collect styles into a separate file.

Can add an option?
```
new VuetifyLoaderPlugin({
  includeVuetifyStyles: false
})
```

**Comment by KaelWD** [comment]
```js
{
	  enforce: 'pre',
	  test: /\.css$/,
	  include: /node_modules\/vuetify\//,
	  issuer: /node_modules\/vuetify\//,
	  loader: 'null-loader',
}
```

This is handled in the vite plugin with `styles: 'none'` and soon in v2 of the webpack plugin.
