### ISSUE TITLE
[@vuetify/vite-plugin] Unable to override some of the variables

### ISSUE THREAD

**Issue by lukeromanowicz** [vuetifyjs/vuetify-loader#204]
When using vite-plugin 1.0.0-alpha.3 with vuetify 3.0.0-alpha.11 and trying to override variables, some of them don't seem to work (change is not applied) e.g.
```
@use 'vuetify/styles' with (
  $body-font-family: 'monospace', // this works fine
  $typography: ( // as well as this
    'h1': (
      'size': 1rem,
      'weight': 900,
      'line-height': 1rem,
      'letter-spacing': -.015625em,
      'text-transform': none
    ),
  ),
  $grid-breakpoints: ( // this doesn't work
    'xs': 0,
    'sm': 1000px,
    'md': 1200px,
    'lg': 1400px,
    'xl': 1600px,
    'xxl': 1800px,
  ),
  $container-max-widths: ( // nor does this
    'md': 1199px,
    'lg': 1399px,
    'xl': 1599px,
    'xxl': 1799px,
  ),
);
```
working `$body-font-family`:
![image](https://user-images.githubusercontent.com/46789227/133410975-70dd5011-6cab-4b88-9222-e00be9e9c380.png)

not working breakpoints:
![image](https://user-images.githubusercontent.com/46789227/133411230-b0649fe5-1529-4aa8-bae2-d6e95dbb213c.png)

**Comment by KaelWD** [comment]
- Are you using `styles: 'expose'`?
- What OS and nodejs version?

**Comment by lukeromanowicz** [comment]
> Are you using styles 'explose'

> How are you importing vuetify?
https://github.com/vuetifyjs/vuetify-loader/tree/next/dev

> What OS and nodejs version?
 Ubuntu 20.04, Node 14 LTS

**Comment by lukeromanowicz** [comment]
repro: https://github.com/lukeromanowicz/vuetify-loader

**Comment by KaelWD** [comment]
This might not work properly with the current alpha, it works for me in the vuetify-loader dev environment with the vuetify next branch symlinked.

**Comment by lukeromanowicz** [comment]
@KaelWD I confirm that it's working great on latest, non-published vuetify

**Comment by KaelWD** [comment]
You can install `vuetify@npm:@vuetify/nightly@next` to use the latest build

**Comment by BreizhReloaded** [comment]
Hello,
I'm reopening that issue, because I still experience some issues. Here is my setup:

```scss
// main.scss
@use 'vuetify/styles' with (
  $typography: (
    'button': (
      'text-transform': none
    ),
  )
);
````

```ts
// vuetify.js
import '../main.scss';
import { createVuetify } from 'vuetify';
export default createVuetify({});
```

```ts
// vite.config.ts
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import vuetify from '@vuetify/vite-plugin';

export default defineConfig({
  plugins: [
    vue(),
    vuetify({ styles: 'expose' })
  ],
});
```

My buttons are not written with the regular case. The `.v-btn` still contains `text-transform: uppercase`. The only workaround I found at the moment, is to manually add the .sass file of the component:

```scss
// main.scss
@use 'vuetify/lib/components/VBtn/VBtn';
```

Am I missing something, or is it a bug? Let me know for more details.
Vuetify v3.0.0-alpha.11, Vue v3.2.6 and Vite plugin v1.0.0-alpha.4.

**Comment by glen-84** [comment]
@BreizhReloaded, Kael said to use `@vuetify/nightly`, but you're using `3.0.0-alpha.11`?

**Comment by BreizhReloaded** [comment]
I gave a try at the nightly yesterday and I've just recheched:
* `main.css` import updated to `@use '@vuetify/nightly/styles'`
* `vuetify.ts` import updated to `import { createVuetify } from '@vuetify/nightly';`
* no change to `vite.config.ts`

I'm getting "_Internal server error: This variable was not declared with !default in the @used module._". I'm using `"3.0.0-next-20210917.0`.

Any other change to perform?

**Comment by BreizhReloaded** [comment]
I completely removed the regular Vuetify from the project, I got "_failed to load config from C:\Users\franc\Projects\opale\front-office\vite.config.ts Error: Cannot find module 'vuetify/dist/json/importMap.json'_". How can I reference the right version?

**Comment by glen-84** [comment]
Read Kael's last message again. Hint: The package name stays `vuetify`, you use an alias.

**Comment by BreizhReloaded** [comment]
I tried it first, but I encountered this error: "_Missing ".onents/VApp/index.mjs" export in "@vuetify/nightly" package_", so I moved to a regular install. 

Nevermind, that gets to complicated for a simple check, I'll wait for the next alpha version. Thank you for your time and help!

**Comment by KaelWD** [comment]
There was a vite bug: https://github.com/vitejs/vite/issues/4957

There's also #206 which I'm looking into

**Comment by BreizhReloaded** [comment]
Ok, that gets interesting. From the Vite template: Vuetify nightly, Vite 2.6.0-beta.2, Vite plugin 1.0.0-alpha.4, I still face the same behaviour. I pushed the code [here](https://github.com/BreizhReloaded/my-vue-app).

**Comment by lukeromanowicz** [comment]
Same here, Vite 2.6.0-beta.4, Vite plugin 1.0.0-alpha.4, Vuetify nightly 3.0.0-next-20210924.0. The problem described in the first post still exists.

**Comment by glen-84** [comment]
@KaelWD I seem to have the same problem with webpack. Would you please consider reopening this issue?

**Comment by glen-84** [comment]
@KaelWD I'm not using vue-cli. I'll test again later today, and create a repro if necessary. Thanks.

**Comment by glen-84** [comment]
@BreizhReloaded Which OS are you using?

**Comment by BreizhReloaded** [comment]
Windows 10 Version 21H1 Build 19043.1237.

**Comment by glen-84** [comment]
This could be a Windows-specific issue. I'm on Windows as well, but using webpack.

**Comment by glen-84** [comment]
@KaelWD,

Now that we know what the issue is, are you planning on pushing a fix, or do you want someone to send a PR?

**Comment by jpiombo** [comment]
Is there a way to overrride component variables. 
I.E, some default variables work:
```

  $color-pack: true,
  $utilities: false,
  $body-font-family: 'Inter',
```

However if I try to use component variables like : $button-text-letter-spacing:0px I start getting errors. 

`[vite:css] [sass] This variable was not declared with !default in the @used module.
  ╷
5 │ ┌    $button-text-letter-spacing:0px
6 │ └ 
  ╵
  src/settings.scss 5:4                            @use
  plugin-vuetify:components/VGrid/VGrid.sass 1:1  root stylesheet
file: plugin-vuetify:components/VGrid/VGrid.sass`

**Comment by ajberasategui** [comment]
@jpiombo make sure you're:
Using latest nightly Vuetify and Vite plugin.
using variables on "vuetify/settings" and not just "vuetify".
