### ISSUE TITLE
Vite loader not working when server.open is used and expose option is used

### ISSUE THREAD

**Issue by MichalMeszaros** [vuetifyjs/vuetify-loader#206]
Configuration:
  "vite": "^2.5.10",
  "@vuetify/vite-plugin": "1.0.0-alpha.4",
  "vuetify": "3.0.0-alpha.11"

vuetify({ styles: 'expose' }), <- configuration of vuetify loader
server.open = true; <- configuration of vite

Problem:
css files in the vuetify component are not replaced with sass files and therefore i am unable to override any sass variable.
When i dig deeper i find that the problem is in stylesPlugin.js file where it did not recognized that the file is loaded from the vuetify component.
`
async resolveId(source, importer, custom) {
            if (importer &&
                source.endsWith('.css') &&
                isSubdir(vuetifyBase, importer)) {
`
when i did print out the **importer** and **source** parameters this is output
`
node_modules/.vite/vuetify_lib_components_VGrid_index_mjs.js?v=1e6b2180 /node_modules/vuetify/lib/components/VGrid/VGrid.css
`
and therefore the **isSubdir(vuetifyBase, importer)** will not be true.

**Comment by KaelWD** [comment]
https://github.com/vitejs/vite/issues/3124
