### ISSUE TITLE
[Bug Report] invalid typing for vuetify

### ISSUE THREAD

**Issue by MichalMeszaros** [vuetifyjs/vuetify-loader#208]
### Environment

**Browsers:** Chrome 93.0.4577.82
**OS:** Windows 10

### Steps to reproduce
index.ts (my vuetify plugin)
```
import 'vuetify/styles';
import { createVuetify } from 'vuetify';
```

### Expected Behavior
after runing vite i expect that this will result in builded app

### Actual Behavior
recieved error during build
```
src/plugins/vuetify/index.ts:3:10 - error TS2614: Module '"vuetify"' has no exported member 'createVuetify'. Did you mean to use 'import createVuetify from "vuetify"' instead?

3 import { createVuetify } from 'vuetify';
```

### Reproduction Link
<a href="" target="_blank"></a>

**Comment by KaelWD** [comment]
This isn't related to vuetify-loader.
