### ISSUE TITLE
Progressive Images does not work with `@vue/cli-service@5.0.0-beta.7`

### ISSUE THREAD

**Issue by alireza4050** [vuetifyjs/vuetify-loader#218]
vue-cli 5.0.0-beta.7 has removed `url-loader` and `file-loader` in favor of the newly added [Assets Modules](https://webpack.js.org/guides/asset-modules/) feature in webpack 5.

**Comment by KaelWD** [comment]
See d5446df4c54132de1387e6d5c62ba5d2d7f1377c

**Comment by alireza4050** [comment]
Well I guess I'll patch `vue-cli` for the time being. Is there any plan to change this in `vuetify-loader`?
