### ISSUE TITLE
The `null-loader` is deprecated

### ISSUE THREAD

**Issue by glen-84** [vuetifyjs/vuetify-loader#220]
- https://webpack.js.org/blog/2020-10-10-webpack-5-release/#deprecated-loaders
- https://github.com/webpack-contrib/null-loader

There's a tiny chance that using `resolve.alias` instead would behave differently and eliminate the MCEP `Conflicting order` warnings ... but probably not. 🙃

<details>
    <summary>Example warning</summary>

    WARNING in chunk vendors-node_modules_vuetify_lib_components_VAvatar_VAvatar_mjs-node_modules_vuetify_lib_comp-6b0495 [mini-css-extract-plugin]
    Conflicting order. Following module has been added:
     * css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-1.use[2]!../../node_modules/null-loader/dist/cjs.js!../../node_modules/vuetify/lib/components/VAvatar/VAvatar.css
    despite it was not able to fulfill desired ordering with these modules:
     * css ../../node_modules/css-loader/dist/cjs.js!../../node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-1.use[2]!../../node_modules/null-loader/dist/cjs.js!../../node_modules/vuetify/lib/components/VBtn/VBtn.css
       - couldn't fulfill desired order of chunk group(s) ,
</details>

(PS. I have set `ignoreOrder: true`, but it still kinda bothers me.)

**Comment by KaelWD** [comment]
`resolve.alias` doesn't support regexp or `issuer`

The conflicting order warnings are unrelated: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250
