### ISSUE TITLE
Unable to access Vuetify Sass module configuration

### ISSUE THREAD

**Issue by glen-84** [vuetifyjs/vuetify-loader#221]
(as discussed Kael on Discord)

https://github.com/glen-84/vuetify-loader-issue

If you try to forward the configured Vuetify Sass module with something like:

**main.scss**
```scss
@forward "vuetify/styles" with
    (
        $body-font-family: "monospace"
    );
```

**app.vue**

```html
<style lang="scss" scoped>
@use "./main" as x;

a {
    font-family: x.$body-font-family;
}
</style>
```

You see two different types of errors:

1. `modulesTypeError: options.awaitResolve is not a function`
2. `SassError: This variable was not declared with !default in the @used module.`

---

![image](https://user-images.githubusercontent.com/261509/142867637-b57db90f-c50b-4333-bf61-70655ba54ab9.png)

---

@KaelWD What is the best way forward here? (excuse the pun)

If this is not possible, should developers manually import the Sass files?

**Comment by KaelWD** [comment]
I'd say with the current way of forwarding variables that this depends on https://github.com/sass/sass/issues/2745
We need to be able to call `sass.render()` on the component styles without re-loading all of vuetify, and then pass just that one module back to vue-loader so the scoped selectors can be added.

**Comment by glen-84** [comment]
> I'd say with the current way of forwarding variables that this depends on [sass/sass#2745](https://github.com/sass/sass/issues/2745) We need to be able to call `sass.render()` on the component styles without re-loading all of vuetify, and then pass just that one module back to vue-loader so the scoped selectors can be added.

It looks like this might be available in [Sass 1.45](https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1450-rc1), if I'm understanding correctly.

**Comment by KaelWD** [comment]
Not quite. It looks like it will make the import replacement more robust because it can be done with an importer now instead of relying on webpack/vite, but there's still no stateful compiler.

**Comment by BreizhReloaded** [comment]
Hello and happy new year gentlemen!

I've been facing something similar: are we talking about reusing elsewhere in the project the overridden Vuetify set of Sass variables? Extending a bit glen-84's example, how can I `@use` the Vuetify settings, but including with my own values?

Something like that:

**main.scss**
```scss
@forward "vuetify/styles" with (
    $body-font-family: "monospace"
);
```

**app.vue**
```vue
<style lang="scss" scoped>
@use "./main" as x;

a {
    font-family: x.$body-font-family;
    font-size: x.$font-size-root
}
</style>
```

**Comment by kouts** [comment]
It would be useful to have a way of getting the Vuetify SCSS vars inside Vue components.

**Comment by jd-solanki** [comment]
I am theme vendor and I have two SCSS files from where vuetify SCSS variables can be overridden. However, the issue is we can't do the below at the moment:

```scss
@forward "vuetify/styles" with (
    $border-radius-root: 10px !default,
);

@use "vuetify/styles";

.v-btn {
    border-radius: styles.$border-radius-root;
}
```

![image](https://user-images.githubusercontent.com/47495003/170948637-2f4318e3-9d86-4500-8cda-a19a5c64a8a5.png)

I tried the same without vuetify and everything is working perfectly.

I have reproduced the example: https://github.com/jd-solanki/vuetify-scss

`main` branch: Pure SCSS implementation **(Working as expected)**
`vuetify-issue`: Trying to override vuetify SCSS vars from multiple files 😢

**Comment by jd-solanki** [comment]
If there is a workaround using the old `@import` I am happy to do that. Did anyone tried?

**Comment by BreizhReloaded** [comment]
Same problem here. My current workaround is:

1. Create a dedicated custom `settings.scss` with all the needed variable in it:
```scss
// settings.scss
$border-radius-root: 10px !default;
```

2. In your `main.scss`:
```scss
@use "./settings" as settings;
@use "vuetify/styles" as vuetify with (
  $border-radius-root: settings.$border-radius-root;
);
```

3. Anywhere else in your app:
```scss
@use "./settings" as settings;
// Use you custom settings variables
```

**Comment by BreizhReloaded** [comment]
It would be nice indeed to be able to override variable without the need to rewrite each variable, and to reuse overridden values easily.

**Comment by throrin19** [comment]
Same problem here with override variables and I have another question. How to use vuetify variables in our application ?

I try this :  

- `main.scss` : 
    ```scss
    @use 'vuetify/styles';

    // our styles
    @use './common/errors.scss';
    ```
- in one of our component :  
    ```vue
    <style>
    @use '@/styles/main.scss' as main;

    .my-box-example {
        border-right: 1px solid map-get(main.$grey, 'lighten-2');
    }
    </style>
    ```

I have the error in compilation of the scss part `Error: Undefined variable.`

**Comment by KaelWD** [comment]
You can't currently

**Comment by throrin19** [comment]
I have this error when I try to do this : 

```
Error: Can't find stylesheet to import.
    ╷
  2 │ @use 'vuetify/styles/settings'
    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    src/modules/login/components/Container.vue 2:1  root stylesheet
  ```

**Comment by shadow7412** [comment]
I got the default thing working for root level variables (ie, $font-size-root) but for ones that are defined in modules (btn-text-transform) I get the "not declared with !default in the @used module" error.

Any ideas?

```
@use "vuetify/styles" with (
    $font-size-root: 12px, // works
    $btn-text-transform: none, // breaks
);
```

**Comment by KaelWD** [comment]
I added support for `meta.load-css()` in 29039f37eca66c8c46744fd87c6d181af9e9d64b, you might be able to do something with that.

**Comment by throrin19** [comment]
@KaelWD We can use this like that ? 

```scss
@use "sass:meta";

@use meta.load-css(
  "vuetify/styles",
  $with: (
    $color-pack: false,
    $utilities: false,
  )
);
```

**Comment by jd-solanki** [comment]
Thanks @KaelWD for this feature. With this I can create multiple vuetify SCSS config to let them override each other:

```scss
@use "sass:meta";
@use "sass:map";
@use "@/styles/variables" as userVariables;

$vuetify-overrides: (
 // ... Template overrides
);

@include meta.load-css("vuetify/styles", $with: map.deep-merge($vuetify-overrides, userVariables.$vuetify-overrides));
```

Above snippet uses configuration like this: Vuetify < Template < User.

However, we can't use this configured vuetify in our stylesheet. e.g. I can't access `$card-elevation`.

`sass:meta` [docs](https://sass-lang.com/documentation/modules/meta#load-css).

Thanks 🙏🏻

**Comment by BreizhReloaded** [comment]
Oh, that's really interesting. Can't you deep merge the different sets into an other variables, and `@use` that variable?

> I have this error when I try to do this :
> 
> ```
> Error: Can't find stylesheet to import.
>     ╷
>   2 │ @use 'vuetify/styles/settings'
>     │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     ╵
>     src/modules/login/components/Container.vue 2:1  root stylesheet
> ```

Using `@use "vuetify/styles/settings/_index" as settings;` works for me.

**Comment by throrin19** [comment]
When I try to do the `meta.load-css`, I have the error `This variable was not declared with !default in the @used module.`

This is my script (the `meta.load-css` can only used with include)

```scss
@use './variables' as vars;

@use "sass:meta";

// our styles
@use './common';

@include meta.load-css(
  "vuetify/styles",
  $with: (
    $body-font-family: vars.$aq-body-font-family,
    $heading-font-family: vars.$aq-heading-font-familly,
  )
);
```

**Comment by wheelebin** [comment]
Has anyone been able to successfully customize vuetify and use vuetify sass variables elsewhere in their application using the meta.load-css function or any other approach that might exist?

**Comment by KaelWD** [comment]
This seems to work for me:
```scss
// main.scss
@use './settings';
@use 'vuetify/styles';
```
```scss
// _settings.scss
@forward 'vuetify/lib/styles/settings' with (
  $color-pack: false,
  $container-max-widths: (
    xs: null,
    sm: null,
    md: 768px,
    lg: 1250px,
    xl: 1800px,
    xxl: 2300px,
  ),
);

@forward 'vuetify/dist/component-variables' with (
  $button-height: 56px,
);
```
```scss
// App.vue
<style lang="scss">
  @use './settings';
  
  @debug settings.$button-height;
</style>
```

Or if having it split between general and component variables is too confusing:
```scss
// _vuetify.scss
@forward 'vuetify/lib/styles/settings';
@forward 'vuetify/dist/component-variables';
```
```scss
// _settings.scss
@forward './vuetify' with (
  $color-pack: false,
  $container-max-widths: (
    xs: null,
    sm: null,
    md: 768px,
    lg: 1250px,
    xl: 1800px,
    xxl: 2300px,
  ),
  $button-height: 56px,
);
```

**Comment by KaelWD** [comment]
This is now officially supported and I've updated the documentation: https://next.vuetifyjs.com/en/features/sass-variables/

**Comment by throrin19** [comment]
thanks @KaelWD but after try this, I have this error :  

```
[plugin:vite:css] Can't find stylesheet to import.
   ╷
14 │ ┌ @forward 'vuetify/settings' with (
15 │ │   $body-font-family: $aq-body-font-family,
16 │ │   $heading-font-family: $aq-heading-font-familly,
17 │ │ );
   │ └─^
   ╵
  src/styles/_variables.scss 14:1  @use
  src/styles/main.scss 1:1         root stylesheet
  ```

**Comment by KaelWD** [comment]
I had that if I enabled `api: 'modern'` with webpack, haven't seen it with vite.

**Comment by KaelWD** [comment]
You need the next vuetify beta, currently only in nightly.

**Comment by throrin19** [comment]
Ok, In my case, I use vite. I will waiting the next vuetify beta :) Thank you

**Comment by alokVishu** [comment]
Is anyone using the windows system? I am facing a sass override issue: https://github.com/vuetifyjs/vuetify/issues/15763

Sass override is working fine in the Mac system.

**Comment by riodw** [comment]
This helped me

- https://github.com/vuetifyjs/vuetify/issues/16593#issuecomment-1420162611

**Comment by sneko** [comment]
> You need the next vuetify beta, currently only in nightly. `vuetify/styles/settings` doesn't include components so it won't be applied consistently.

@KaelWD on my side it works to change `$body-font-family` with something like:
```scss
@use 'vuetify' with (
  $heading-font-family: ('Marianne', Verdana, arial),
)
```

but indeed if I set `$border-radius-root` it won't change the style for components. What's the hack to do so? I tried multiple things like mentioned into https://github.com/vuetifyjs/vuetify-loader/issues/221#issuecomment-1227305722 but it does not work.

Also, I tried to change my strategy to use `vite-plugin-vuetify` thinking it would help building `.css` of components with my custom settings... but it breaks my project (saying as error: `[Vuetify] Could not find defaults instance`) so unable to say if this would solve the problem.

Any idea?

**Comment by MariiaRiabinina** [comment]
hello everyone! @sneko could you help me, please? Did you find a solution?

**Comment by joao5142** [comment]
same issue ,i m currently using nuxt  +vite +vuetify ,  my nuxt version is 3.7 and vuetify 3.3 , i downloaded a lot of packages  and it's not working i also 
![image](https://github.com/vuetifyjs/vuetify-loader/assets/45145741/b92136de-7b96-4503-9735-afc5854e139d)

**Comment by kroawen** [comment]
same issue
