### ISSUE TITLE
[VuetifyLoaderPlugin Error] No matching rule for vue-loader found. when setting up treeshaking

### ISSUE THREAD

**Issue by willbicks** [vuetifyjs/vuetify-loader#224]
Hi all, I am getting the same error as described in #161 and #162 , but have been able to replicate it again while following the exact steps described in [treeshaking instructions](https://vuetifyjs.com/en/features/treeshaking) on a clean project.

### Steps to reproduce:

- `vue create vuetify-treeshake-test` (Vue 2 default preset selected)
- `cd vuetify-treeshake-test`
- `vue add vuetify` (Default preset selected)
    - `npm run serve` completes successfully at this stage and the vuetify default page is visible.
- Following steps outlined in [treeshaking instructions](https://vuetifyjs.com/en/features/treeshaking) for vue-cli projects...
    - Update `./src/plugins/vuetify.js`:
      ```
      import Vue from 'vue';
      import Vuetify from 'vuetify/lib';
      
      Vue.use(Vuetify);
      
      export default new Vuetify({
      });
      ```
    - Update `./vue.config.js`:
      ```
      const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin')
      
      module.exports = {
        transpileDependencies: [
          'vuetify'
        ],
        configureWebpack: {
          plugins: [
            new VuetifyLoaderPlugin()
          ],
        },
      }
      ```
- `npm run serve`

### Expected result:

Vue project compiles and is served, and the VuetifyLoaderPlugin packs required vuetify components into js bundles.

### Actual result:

`npm run serve` fails with the following message:

```
Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader and VuetifyLoaderPlugin is applied after VueLoaderPlugin.
    at VuetifyLoaderPlugin.apply (C:\Users\bicks\Documents\vuetify-treeshake-test\vuetify-treeshake-1\node_modules\vuetify-loader\lib\plugin.js:15:13)
    at webpack (C:\Users\bicks\Documents\vuetify-treeshake-test\vuetify-treeshake-1\node_modules\webpack\lib\webpack.js:51:13)
    at serve (C:\Users\bicks\Documents\vuetify-treeshake-test\vuetify-treeshake-1\node_modules\@vue\cli-service\lib\commands\serve.js:163:22)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuetify-treeshake-1@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vuetify-treeshake-1@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by KaelWD** [comment]
If you have both vue-cli-plugin-vuetify and vuetify-loader installed you do not need the configureWebpack section, that's already done automatically.

**Comment by qxygene** [comment]
Having same issue, is there any solution on this?
