### ISSUE TITLE
[vite-plugin] Type definition for ESM prevents default importing

### ISSUE THREAD

**Issue by josh-hemphill** [vuetifyjs/vuetify-loader#227]
When importing through typescript in an ESM project, there's no default export type. Using `allowSyntheticDefaultImports` can fix it, but it changes the runtime import signatures of all CJS dependencies.

Either having a bundle/dts for ESM or just adding a type entry to the current `.d.ts` for default export would solve this.

**Comment by KaelWD** [comment]
Does just adding `export default ...` next to the existing `export = ` work or is it more complex than that?

**Comment by josh-hemphill** [comment]
Just tested it some more, and unfortunately typescript assumes incompatibility if it sees `export =` anywhere, regardless of other exports. The typing for CJS seems to still work when just `export default` is used, so if reusing the `.d.ts` file, replacing the export directive might be the only way to go.

**Comment by rayfoss** [comment]
I ran into this same issue while trying to hijack the module and importMap.json to run on vutify v2 with vite + vue2-vite-plugin... no cigar. That said vuetify 2 on vite is working surprisingly well on a 3 year old project, aside from having to manually declare all my components. My tsconfig has allowSyntheticDefaultImports, but my IDE is ignoring it for some odd reason, vite reads tsconfig correctly and doesn't complain.

**Comment by ThePrincelle** [comment]
> I ran into this same issue while trying to hijack the module and importMap.json to run on vutify v2 with vite + vue2-vite-plugin... no cigar. That said vuetify 2 on vite is working surprisingly well on a 3 year old project, aside from having to manually declare all my components. My tsconfig has allowSyntheticDefaultImports, but my IDE is ignoring it for some odd reason, vite reads tsconfig correctly and doesn't complain.

I'm having some troubles with the file importMap.json. Vite tells me it cannot find it. Did you find a solution to the problem?
