### ISSUE TITLE
Inconsistent css in development vs production

### ISSUE THREAD

**Issue by adi-zz** [vuetifyjs/vuetify-loader#23]
I have [this example project](https://github.com/adi-zz/css-in-dev-vs-prod/) (created with [create-nuxt-app@7dd7c34](https://github.com/nuxt/create-nuxt-app/tree/7dd7c345aa1f378a1174d79b51207e37922af05c), it has [Nuxt 2 with CSS Extraction](https://nuxtjs.org/api/configuration-build/#extractcss) and [Vuetify 1.3 with a-la-carte with vuetify-loader](https://vuetifyjs.com/en/guides/a-la-carte#vuetify-loader)).

If you start the project on dev, the `Welcome to the Vuetify + Nuxt.js template` in homepage will be red, but in prod mode, it will be black. This is because the order 2 [css](https://github.com/adi-zz/css-in-dev-vs-prod/blob/30cd433b5e04579a9d114f137cbc23dc8d6dd352/pages/index.vue#L68-L69) [rules](https://github.com/vuetifyjs/vuetify/blob/dev/src/stylus/components/_cards.styl#L5-L8) are loaded in, in dev and prod is different.

Based on this [comment](https://forum.vuejs.org/t/css-loading-order-with-webpack/33814/3), I tried to change the order in which vuetify components and project own components are imported in [vuetify-loader](https://github.com/vuetifyjs/vuetify-loader/blob/b0a22c03e03600900604352592933e107130d26f/lib/loader.js#L49-L70), but that didn't help.

Not sure if this issue is vuetify-loader related, I saw similar discussions but couldn't find a solution. Maybe you have an idea on how to deal with this.

**Comment by KaelWD** [comment]
I don't think that's related to this project. We just add js imports, there's no special css handling.

**Comment by adi-zz** [comment]
I also reproduced this issue in a simpler Nuxt project (Vuetify not used at all).
Let's see how that [issue](https://github.com/nuxt/nuxt.js/issues/4204) will be solved.

**Comment by KaelWD** [comment]
Yeah it's probably got something to do with the way they do CSS extraction, nothing actionable here imo.
