### ISSUE TITLE
Failed to resolve component: *

### ISSUE THREAD

**Issue by FerdinandFidel** [vuetifyjs/vuetify-loader#231]
Hello everybody, 

i got this errors: 
`Failed to resolve component: v-list-item-content`

My setup looks like this: 

` "dependencies": {
    "@mdi/font": "5.9.55",
    "roboto-fontface": "*",
    "vue": "^3.2.25",
    "vue-router": "^4.0.13",
    "vuetify": "^3.0.0-alpha.0",
    "webfontloader": "^1.0.0"
  },` 
  ` "devDependencies": {
    "@vitejs/plugin-vue": "^2.2.0",
    "@vue/cli-plugin-babel": "5.0.0-beta.7",
    "@vue/cli-service": "5.0.0-beta.7",
    "@vuetify/vite-plugin": "^1.0.0-alpha.3",
    "sass": "^1.38.0",
    "sass-loader": "^10.0.0",
    "vite": "^2.8.0",
    "vue-cli-plugin-vuetify": "~2.4.5",
    "vuetify-loader": "^2.0.0-alpha.0"
  }`

I used this instruction to install it: https://next.vuetifyjs.com/en/getting-started/installation/#vite

Maybe someone can give me a hint why some components can not be loaded. 

Many greetings

**Comment by KaelWD** [comment]
It doesn't exist anymore. Upgrade guide is coming soon.
