### ISSUE TITLE
Stylesheets not generated with vue-cli-5 vue.config.js css option: droping css module naming

### ISSUE THREAD

**Issue by KevinFabre** [vuetifyjs/vuetify-loader#234]
**Environment**

- vue-cli: 5.0.x
- vue-loader: 1.7.x
- sass: ~1.32.0
- sass-loader: ^8.0.0

**Steps to reproduce**

1. Create a vue 2 project with vue-cli 5.0.x and add Vuetify
2. All default configuration.
3. Create a `styles/variables.scss` file.
4. Configure css options to drop xxx.module.scss in vue.config.js. https://cli.vuejs.org/guide/css.html#css-modules
5. Serve the app

**Actual Behavior**

All Vuetify stylesheets have been generated.

**Expected Behavior**

Some Vuetify stylesheets have not been generated.

![Screenshot 2022-03-29 at 15-20-54 hello-vue-cli-5](https://user-images.githubusercontent.com/48985996/160620645-21bd055f-198b-4c73-b3dc-09a1ea57d09d.png)

**Reproduction Links**

- With css options added: https://github.com/KevinFabre/vue-cli-5-vuetify-scss-variables-in-js/tree/error/vuetify-style
- Working with xxx.module.scss files: https://github.com/KevinFabre/vue-cli-5-vuetify-scss-variables-in-js

Shouldn't we use this option https://cli.vuejs.org/guide/css.html#css-modules when having a `styles/variables.scss` file ?

**Comment by yisibell** [comment]
I have the same problem in the nuxt2 project. The deployment environment is Linux, but macOS and Windows is ok.

**Comment by genygilles** [comment]
@yisibell We found a workaround, you should have a look at https://stackoverflow.com/q/71709928/3049002 and https://github.com/KevinFabre/vue-cli-5-vuetify-scss-variables-in-js/pull/1 https://github.com/KevinFabre/vue-cli-5-vuetify-scss-variables-in-js/pull/2 :wink:

**Comment by KaelWD** [comment]
This 
- won't be supported
- isn't related to this package, vuetify itself would have to use css modules for this to work
