### ISSUE TITLE
Vuetify 3 with vite, @vuetify/vite-plugin or vuetify-loader@next

### ISSUE THREAD

**Issue by Zehir** [vuetifyjs/vuetify-loader#236]
Hello here,

I try to add Vuetify 3 in a new project using the template [vitesse](https://github.com/antfu/vitesse).

This is what I did to install it ; https://github.com/antfu/vitesse/discussions/174#discussioncomment-2758509
It's working but the compilation don't work.
It's look like I need to use the vuetify-loader instead but I can't install it for some reason.

Also first question, there is two packages that look similar but I don't know which one I need to use;
- [vuetify-loader@next](https://www.npmjs.com/package/vuetify-loader/v/2.0.0-alpha.9)
- [@vuetify/vite-plugin](https://www.npmjs.com/package/@vuetify/vite-plugin)

**Comment by Zehir** [comment]
The [webpack plugin](https://www.npmjs.com/package/webpack-plugin-vuetify) has been published with the new name but not the [other one](https://www.npmjs.com/search?q=vite-plugin-vuetify) vite-plugin-vuetify.
Also the Homepage link lead to a 404 error

**Comment by KaelWD** [comment]
Come back tomorrow
```
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/vite-plugin-vuetify - vite-plugin-vuetify cannot be republished until 24 hours have passed.
```
