### ISSUE TITLE
[Feature Request] Vite plugin - automatic alias support (transformAssetUrls)

### ISSUE THREAD

**Issue by TechAkayy** [vuetifyjs/vuetify-loader#237]
### Problem to solve
Adding this feature request based on @KaelWD's advise on discord (https://discord.com/channels/340160225338195969/660898563139567625/927090271068491856) about having vuetify vite plugin to automatically support 'transformAssetUrls'. 

Current workaround is to define 'transformAssetUrls' in the vite.config.js manually for a list of components like this:
```		
vue({
  template: {
    transformAssetUrls: {
      'v-img': ['src', ':src'],
      'v-parallax': ['src'],
      // other tags.... 
    }
  }
}),
```

https://stackblitz.com/github/TechAkayy/vuetify3-beta-alias-support (v-img doesn't show, unless comments in vite.config.js for transformAssetUrls inside vue() are removed)

### Proposed solution
Support alias resolution automatically for all vuetify tags via `vite-plugin-vuetify`

**Comment by KaelWD** [comment]
Couldn't be done automatically in vite, so I added it as an export instead. 

```js
vue({ 
  template: { transformAssetUrls }
}),
```
