### ISSUE TITLE
[Bug Report][2.6.0] Vuetify components conflicts with vue-template-loader

### ISSUE THREAD

**Issue by MohammedSaberMohammed** [vuetifyjs/vuetify-loader#238]
### Environment
**Vuetify Version:** 2.6.0
**Vue Version:** 2.6.14
**Browsers:** Chrome 102.0.5005.61
**OS:** Linux x86_64

### Steps to reproduce
The reproduction link seems working fine but I don't know why it's happening with me.
I created a [Stackoverflow question](https://stackoverflow.com/questions/72456336/vue-template-loader-breaks-vuetify-components)

### Expected Behavior
Load Components without importing them individually as it was before install vue-template-loader

### Actual Behavior
Styles and components are gone and errors in console says 
`[Vue warn]: Unknown custom element: <v-spacer> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

### Reproduction Link
<a href="https://codesandbox.io/s/brave-lamarr-8npxgf?file=/src/main.js" target="_blank">https://codesandbox.io/s/brave-lamarr-8npxgf?file=/src/main.js</a>

**Comment by KaelWD** [comment]
vuetify-loader supports `<template src="...`

vue-template-loader doesn't seem to be very popular, I don't think it's worth my time adding support for it
