### ISSUE TITLE
[Vite & Nuxt] Vuetify plugin must be loaded after the vue plugin

### ISSUE THREAD

**Issue by brownsugar** [vuetifyjs/vuetify-loader#239]
Hi, after updating this plugin from `@vuetify/vite-plugin@1.0.0-alpha.10` to `vite-plugin-vuetify@1.0.0-alpha.11`, it throws error message when starting Nuxt.

```
ERROR  Cannot start nuxt:  Vuetify plugin must be loaded after the vue plugin
```

<img width="752" alt="image" src="https://user-images.githubusercontent.com/2935980/173858619-571183ae-af1a-4bb6-901a-e83a8bec787e.png">

I did add the `configResolved` setting in nuxt.config.ts according to [this example code](https://github.com/nuxt/framework/discussions/1183#discussioncomment-1997354).

Reproduce link: https://codesandbox.io/s/dawn-sound-rtl8ig?file=/nuxt.config.ts:314-771

**Comment by KaelWD** [comment]
https://github.com/nuxt/framework/discussions/1183#discussioncomment-1997354

**Comment by TanixLu** [comment]
vue 3.2.38 and vuetify 3.0.0-beta.10, same issue.

A workaround: comment out the three lines of code that throw the error.

![image](https://user-images.githubusercontent.com/56950803/188906147-33ec7cbc-8dec-4820-b7a1-9da19f71d6f2.png)

**Comment by jd-solanki** [comment]
Upgrading to alpha 16 resolves the issue for me

**Comment by jd-solanki** [comment]
vue 3.2.38 has issue with avatar rendering, aren't you facing this: https://github.com/vuejs/core/issues/6573

**Comment by TanixLu** [comment]
> Upgrading to alpha 16 resolves the issue for me

Also works for me

**Comment by KaelWD** [comment]
@brownsugar A nuxt example has been added on https://next.vuetifyjs.com/en/features/treeshaking/

@everyone else #267
