### ISSUE TITLE
[Feature Request] make Vuetify-loader compatible with Vue 2.7

### ISSUE THREAD

**Issue by DRoet** [vuetifyjs/vuetify-loader#240]
Vuetify-loader directly depends on `vue-template-compiler` which won't be required when using 2.7 and vue-loader 15.10.

`@vue/cli` already made compatibility changes in their [v5.0.6 release](https://github.com/vuejs/vue-cli/releases/tag/v5.0.6) but I assume there is more work needed in the Vuetify-loader...

Thoughts @KaelWD ?

**Comment by DRoet** [comment]
[compiler.compile()](https://github.com/vuetifyjs/vuetify-loader/blob/master/lib/loader.js#L137) is also not an available function, which would be the next problem.

**Comment by KaelWD** [comment]
Ugh, I thought it was just an alias like vue/server-renderer
