### ISSUE TITLE
[Vite, Nuxt3, Vuetify3] Could not load ./VCard.sass | styles: 'sass'

### ISSUE THREAD

**Issue by MichaelGitArt** [vuetifyjs/vuetify-loader#241]
### Environment
Vuetify Version: "3.0.0-beta.4"
Nuxt Version: "3.0.0-rc.4"
vite-plugin-vuetify: "1.0.0-alpha.12"
Browsers: Chrome 102.0.0.0
OS: Windows 10

### Desc
When I use style:'sass' mode, I'm receiving errors.
```
vuetify({
  // COMMENT this line and errors will disappear
  styles: 'sass',
}),
```

#### 1
Run 'yarn dev` and  you will see errors in the console. It works well, but error messages are exist,

<img width="663" alt="image" src="https://user-images.githubusercontent.com/34610289/174398400-b8b5d21b-6352-4bd7-852a-73daf722d00a.png">

#### 2
Run 'yarn build' and it fails

<img width="807" alt="image" src="https://user-images.githubusercontent.com/34610289/174400224-10b41f5f-e559-46d8-892a-251cfdbc6abc.png">

###  Actual Behavior
Should just work well

### Reproduction Link

https://stackblitz.com/edit/nuxt-starter-rlzhjo?file=nuxt.config.ts
https://github.com/MichaelGitArt/vite-plugin-vuetify-issue

###  Other comments
I'm trying to customize components styling by variables.

**Comment by KaelWD** [comment]
- Your stackblitz link works without errors
- `styles: 'sass'` was an experiment and probably isn't actually useful, the variables guide is here: https://github.com/vuetifyjs/vuetify-loader/tree/next/packages/vite-plugin#customising-variables

**Comment by primeo-mpniewski** [comment]
@KaelWD this https://github.com/vuetifyjs/vuetify-loader/tree/next/packages/vite-plugin#customising-variables does not working. 
Beside In Vuetify 3.0.0.beta.4, when I use `vuetify({ styles: 'expose' })` and import styles in main.scss using `@use "vuetify/styles"`, thear are missing a lot of default styles.
