### ISSUE TITLE
[Feature Request] Vite3 support

### ISSUE THREAD

**Issue by payammeyer** [vuetifyjs/vuetify-loader#257]
### Problem to solve
It allows users using Vuetify3 with Vite to upgrade to Vite3

### Proposed solution
Bump the version in vite-plugin-vuetify to Vite3 now that it's officially released: https://vitejs.dev/blog/announcing-vite3.html

**Comment by KaelWD** [comment]
Duplicate of #256

**Comment by payammeyer** [comment]
> Duplicate of #256

Odd, sorry, I did look and didn't see #256 when I submitted this one.
