### ISSUE TITLE
Build is bigger than a-la-carte

### ISSUE THREAD

**Issue by mathieucivel** [vuetifyjs/vuetify-loader#26]
Using the same code base, when switching from a-la-carte configuration to using vuetify-loader, we see a 10% increase in build size. 

Before:

<img width="1278" alt="a-la-carte-before" src="https://user-images.githubusercontent.com/509618/47710750-d5033480-dc33-11e8-97ac-c0542787521f.png">

After:

![vuetify-loader-after](https://user-images.githubusercontent.com/509618/47710762-dd5b6f80-dc33-11e8-90f7-38447a208107.png)

It seems that the usage of `vuetify/lib/` instead of `vuetify/es5/` makes the build bigger. Is it possible to remedy this by only importing from `vuetify/es5/` ?

**Comment by KaelWD** [comment]
You still have all the es5 imports, they need to be removed.

**Comment by mathieucivel** [comment]
Ok thanks for the reply, in fact I had this left:

![capture d ecran 2018-10-30 a 12 45 03](https://user-images.githubusercontent.com/509618/47716019-b5730880-dc41-11e8-9fe9-43f970580f3a.png)

I thought I needed to keep VCheckbox because I'm extending it and Vuetify for configuration. But it also works from `lib`. And now the build size is better.

Perhaps a word about it in the README would save time for everybody in the future ?

**Comment by KaelWD** [comment]
Sure. I still need to write a migration guide, but all the /es5 references have been removed from the [documentation](https://vuetifyjs.com/en/guides/a-la-carte).

**Comment by mathieucivel** [comment]
Yes I missed that and only took the GitHub release notes -> vuetify-loader road..
