### ISSUE TITLE
vite-plugin-vuetify breaks when upgrading vite to 3.1.0

### ISSUE THREAD

**Issue by jaromanda** [vuetifyjs/vuetify-loader#267]
The issue is in `importPlugin.ts` line 18. `this` is undefined so the condition fails and `Vuetify plugin must be loaded after the vue plugin` Error is thrown

Simple fix is to change line 18 from

    if (config.plugins.indexOf(this) < ....

to

    if (config.plugins.findIndex(plugin => plugin.name === 'vuetify:import') < ....

**Comment by derHodrig** [comment]
With Version 
`"vite-plugin-vuetify": "^1.0.2",`
and nuxt.config implementation

```
hooks: {
    'vite:extendConfig': (config: any) => {
      config.plugins.push(
        vuetify({
          autoImport: true,
          styles: { configFile: resolve(join(currentDir, '/assets/scss/_variables.scss')) },
        }),
      )
    },
  },
```

This exactly problem comes, if I start [nuxt/storybook](https://storybook.nuxtjs.org/examples/vuetify). Normal dev mode works just fine. Can you say if this is related to "vite-plugin-vuetify"?
