### ISSUE TITLE
HMR fail with Cannot read property 'default' of undefined

### ISSUE THREAD

**Issue by Farkal** [vuetifyjs/vuetify-loader#27]
I am moving to vuetify-loader and each time i remove an old import `import {VAlert} from 'vuetify/lib'` the hot module reload fail and i get a blank page with this error in my console:  
`Uncaught TypeError: Cannot read property 'default' of undefined`

The console say it come from this script (cc-alert is my component where i just remove the old import) were mod seems undefined.
`import mod from "-!../../../node_modules/vuetify-loader/lib/loader.js!../../../node_modules/vue-loader/lib/index.js??vue-loader-options!./cc-alert.vue?vue&type=script&lang=js&"; export default mod; export * from "-!../../../node_modules/vuetify-loader/lib/loader.js!../../../node_modules/vue-loader/lib/index.js??vue-loader-options!./cc-alert.vue?vue&type=script&lang=js&"`

I need to restart my npm task to make it work.

**Comment by KaelWD** [comment]
`mod` is added by vue-loader. I can't say if this is related to vuetify-loader without a reproduction environment.
