### ISSUE TITLE
Nuxt, Windicss, Vuetify: Using custom variables, all styles are broken with nuxt-windicss 

### ISSUE THREAD

**Issue by MichaelGitArt** [vuetifyjs/vuetify-loader#275]
When adding nuxt-windicss module, almost all style disappears.

Here is normal works app with custom variables. There in the README, you will find steps on how to reproduce error. (With codeflow too)
https://github.com/MichaelGitArt/issue-vuetify-windi-conflict
[![Open in Codeflow](https://developer.stackblitz.com/img/open_in_codeflow.svg)](https:///pr.new/MichaelGitArt/issue-vuetify-windi-conflict)

Before:
<img width="371" alt="image" src="https://user-images.githubusercontent.com/34610289/201693569-a9f89a08-5e35-4adc-a340-492a5fde5be4.png">

After:
<img width="429" alt="image" src="https://user-images.githubusercontent.com/34610289/201693665-f322fe5e-6cc1-418b-933f-2b0fe01898aa.png">

**Comment by KaelWD** [comment]
`transformCSS` in `@windicss/plugin-utils` is returning an empty string.
