### ISSUE TITLE
Unmet peer dependency

### ISSUE THREAD

**Issue by Berkmann18** [vuetifyjs/vuetify-loader#28]
It seems that this package relies on `pug` however it doesn't install it in its dependency and it would make sense that it does (if it actually needs it) rather then relying on the user to install it when they don't need it.

**Comment by nekosaur** [comment]
It only needs it if you use pug templates, so having it as a peer dependency is correct. Always installing it means it will be installing an unnecessary dependency if you are _not_ using pug templates, which is probably the norm.

**Comment by Berkmann18** [comment]
@nekosaur But surely there should be a way (e.g: `optionalPeerDependency`) that makes it npm not print errors when it's not installed.
