### ISSUE TITLE
Tree shaking CSS

### ISSUE THREAD

**Issue by laygir** [vuetifyjs/vuetify-loader#291]
Hello,

I am using Vite + Vuetify 3 and there is about 20K lines of unnecessary css in my output.
Is it possible to purge the unused styles from the final bundle or is this Vite's job?

Also not sure if this is the best place to ask this 🙏

**Comment by KaelWD** [comment]
You can disable utility classes: https://vuetifyjs.com/en/features/sass-variables/#basic-usage

Otherwise https://github.com/vuetifyjs/vuetify/issues/3507, https://github.com/vuetifyjs/vuetify/issues/12512, https://github.com/vuetifyjs/vuetify/issues/13724
