### ISSUE TITLE
🐞 dev & prod style differences if we import vuetify component

### ISSUE THREAD

**Issue by jd-solanki** [vuetifyjs/vuetify-loader#293]
Hi kael,

As you already know we are theme vendor ([Materio admin](https://store.vuetifyjs.com/collections/frontpage/products/materio-vuetify-vuejs-admin-template)) on Vuetify store, One of our customers reported a strange issue after checking demo. Afte inspecting the issue we found that vuetify styles behave differently in prod & dev modes.

If you checked the source code of our template we are importing vuetify components at several places for dynamic rendering like below:
```ts
import { VThemeProvider } from 'vuetify/components';

const wrapper = h(VThemeProvider, { theme: 'dark' })
```

Here's the reproduction repo: https://github.com/jd-solanki/sass-vuetify-issue

In there, if you run the development server slider thumb/indicator will be on right (as overridden in `src/@core/scss/template/_components.scss`) and if you generate the build and preview it then the slider thumb will be on left (unexpected) 😨 

> _P.S. Materio admin template don't have these overrides so you won't able to see differences in live demo & development version but this issue is present in the template we are building right now and also in provided reproduction_

Thanks so much ❤️ 

Regards,
Team Materio

**Comment by jd-solanki** [comment]
Hi @KaelWD 

Sorry for the ping but I wanted to let you know that we are on the verge of the new release for materio admin and we are facing serious issues with production deployment that we can't find in dev mode due to the differences.

We will be able to ship new updates on vuetify store quickly if you can take a look if this from vuetify.

Thanks for your time and efforts 😇 

Regards,
Materio team

**Comment by KaelWD** [comment]
This has been a problem forever, we can't really control the order of CSS imports. You just have to make sure your overrides have higher specificity rather than relying on order. 
https://github.com/vuetifyjs/vuetify/issues/15596 should make this easier

**Comment by jd-solanki** [comment]
Hi @KaelWD 

Thanks for your attention. I would like to point out that we only get different styles (CSS order) in dev & prod if we import component from `vuetify/components` as shown in snippet. If I don't import any component that way and use regular auto import I don't get style differences.

Just to confirm, Does the above issue is due to the CSS imports order?

Thanks 😇

**Comment by KaelWD** [comment]
You might want to do `import { VThemeProvider } from 'vuetify/components/VThemeProvider'` anyway which is what auto import uses.

**Comment by jd-solanki** [comment]
Hi @KaelWD 

Thanks for the hint, I can confirm that using imports from actual components (`'vuetify/components/VThemeProvider'`) rather than `vuetify/components` solves the issues.

Thanks so much for the insights.

if you want to resolve this in the future you can re-open it or I'm fine with using actual component imports 😇 

Best Regards 🙏🏻
