### ISSUE TITLE
Webpack federation module

### ISSUE THREAD

**Issue by mflorczak** [vuetifyjs/vuetify-loader#298]
He I have problem because one imported micro frontend is not rendering correctly. Syles were not applied and inside code there are still vuetify tags.  <v-layout> is not correct rendered. Do you know why this is not working proper inside webpack module federation? I have an idea like there is problem with some specific component e.g. <v-layout>.

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/discussions/4068
