### ISSUE TITLE
Is there have any solution to overwrite the vuetify 2 default sass variables when using vite

### ISSUE THREAD

**Issue by dang0705** [vuetifyjs/vuetify-loader#305]

**Comment by KaelWD** [comment]
The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
