### ISSUE TITLE
Labs component not imprted automatically when autoImport is true

### ISSUE THREAD

**Issue by zepa19** [vuetifyjs/vuetify-loader#315]
I noticed, that the labs component are not loaded automatically when the autoImport flag is set to true.

I am using `vite-plugin-vuetify@1.0.2` and `vuetify@3.3.14`.

I quickly checked what this loader is doing and maybe [here is the problem](https://github.com/vuetifyjs/vuetify-loader/blob/c4ead7300f63b702d96945440db6dd61835097dc/packages/shared/src/imports/getImports.ts#L2) - only the `importMap.json` is verified, but the `labs` components are in a separate json file `importMap-labs.json`

**Comment by KaelWD** [comment]
This is intentional, labs components are unstable so it should not be possible to use them inadvertently.

**Comment by zepa19** [comment]
Ok, thanks for the info.

Then I just want to suggest an alternative approach. Maybe an extra flag can be introduced e.g. `autoImportLabComponents` which is set to `false` by default? When this flag is true, then maybe the labs component could be loaded?

No pressure on this one though.
