### ISSUE TITLE
Update transformAssetUrls

### ISSUE THREAD

**Issue by TechAkayy** [vuetifyjs/vuetify-loader#317]
This is a follow-up of this previous one - https://github.com/vuetifyjs/vuetify-loader/issues/237

https://github.com/vuetifyjs/vuetify-loader/blob/master/packages/shared/src/index.ts#L52. The list requires update: 
- VCarouselItem: ['src', 'lazySrc', 'srcset'],
- VCard: ['image'] -> VCard: ['image', 'prependAvatar', 'appendAvatar']

**Comment by TechAkayy** [comment]
Also, will the transformAssetUrls handle url transformation on component aliases correctly? For eg,

``` 
// Vuetify config
aliases: {
    MyCarousel: 'VCarousel', 
},
```

**Comment by KaelWD** [comment]
No, you'll have to add aliases yourself.
