### ISSUE TITLE
vite-plugin-vuetify 1.0.2 deprecated in Vite 5.0 & removed in v6

### ISSUE THREAD

**Issue by JensVanhulst** [vuetifyjs/vuetify-loader#320]
![Screenshot 2023-11-17 at 10 20 41](https://github.com/vuetifyjs/vuetify-loader/assets/43351822/774a8507-8409-4ba4-8eb1-1eae100fe31b)

https://vitejs.dev/guide/troubleshooting.html#cjs

**Comment by donalmurtagh** [comment]
Common JS is [deprecated in Vite 5](https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated) and will be removed in Vite 6. When you use this plugin in Vite 5 it shows a warning to this effect on the console, but the plugin _does_ work in Vite 5.

To make the plugin compatible with Vite 6, an ESM version is needed

**Comment by hrobertson** [comment]
I have `"type": "module"` in my `package.json` so `vite.config.ts` is treated as an ES module. Using Typescript 5.2.2 I'm getting this error on my use of vite-plugin-vuetify:

```
import vuetify from "vite-plugin-vuetify";
const vuetifyPlugins = vuetify({ autoImport: true }),
```

`This expression is not callable.  Type 'typeof import("/home/hamish/my-project/node_modules/vite-plugin-vuetify/dist/index")' has no call signatures.ts(2349)`

Strangely builds seem to be working for now but my project is still WIP so I might yet encounter issues.

Ultimately an ESM version of this package is needed as @donalmurtagh has said.
