### ISSUE TITLE
vite-plugin Node 20 [DEP0170] DeprecationWarning

### ISSUE THREAD

**Issue by admg** [vuetifyjs/vuetify-loader#324]
Hello, I've got an error after migrating from node 18 to 20:

```
(node:3952) [DEP0170] DeprecationWarning: The URL virtual:nuxt:D:/[my_computer_path]/.nuxt/paths.mjs is invalid. Future versions of Node.js will throw an error.               14:45:30  
(Use node --trace-deprecation ... to show where the warning was created)
```

and I found only this thread https://github.com/nuxt/nuxt/issues/24103#issuecomment-1793435036
suggesting that this problem comes from Vuetify Vite Plugin.

Can it be fixed in vite-plugin?

**Comment by GhostvOne** [comment]
same here

**Comment by arcanums** [comment]
> same here
Hi @GhostvOne did you solve this issue? Any workarounds while not fixed.

**Comment by GhostvOne** [comment]
Yes completly removed vuetify

**Comment by iCreatorStudio** [comment]
Same

**Comment by chinesecooly** [comment]
The vuetify official website which version is used

**Comment by sokheangkhun** [comment]
Same here.
