### ISSUE TITLE
Documentation about global imports

### ISSUE THREAD

**Issue by Deraw-** [vuetifyjs/vuetify-loader#33]
Hi!

I'm using this awsome project, and just faced a case where I needed to register some Vuetify components globally.

It's not documented, and so not obvious, but you can add global components while still using automatic import!

See:
```ts
import Vuetify, { VDatePicker, VTextField, VMenu } from 'vuetify/lib';

Vue.use(Vuetify, {
	components: {
		VDatePicker,
		VTextField,
		VMenu
	}
});
```

So maybe you can add documentation for that somewhere?

**Comment by KaelWD** [comment]
It's indirectly mentioned in the documentation already: https://vuetifyjs.com/en/guides/a-la-carte#vuetify-loader

**Comment by Deraw-** [comment]
Oh yeah effectively! Sorry for that useless issue!
