### ISSUE TITLE
what is happening with vite-plugin-vuetify and the latest version of vuetify?

### ISSUE THREAD

**Issue by fablexis** [vuetifyjs/vuetify-loader#333]
Today, for the package `vite-plugin-vuetify` the docs say that its latest version is `2.0.3`:

![image](https://github.com/vuetifyjs/vuetify-loader/assets/7627658/2e25903e-d02f-45b2-861d-496b34d72ede)
https://www.npmjs.com/package/vite-plugin-vuetify?activeTab=versions

 even though when listing the versions of this package: `npm view vite-plugin-vuetify` it says that the latest version is `1.0.2`

![image](https://github.com/vuetifyjs/vuetify-loader/assets/7627658/3a8709c0-d47f-428d-86da-10df312534da)

that's a problem for those who want to update vuetify to its latest version which is `3.5.11`... if you try to make that update, it throws an error like this:

![image](https://github.com/vuetifyjs/vuetify-loader/assets/7627658/e8ccbba8-1e14-4db4-8339-8b9e06b5d0ec)

On the other hand, if I try to use that `2.0.3` version for `vite-plugin-vuetify`, I get this:
![image](https://github.com/vuetifyjs/vuetify-loader/assets/7627658/dcefd077-ace7-4971-a46a-03dcc13b7841)

It makes sense since that version does not exist... but the docs say that it does

**Comment by RobSpectre** [comment]
Also experiencing this.

**Comment by coyotefather** [comment]
I had the same issue, so I updated Vite and vite-plugin-vuetify and that resolved this for me:

`"devDependencies": {
    "@vitejs/plugin-vue": "^4.0.0",
    "eslint": "^8.37.0",
    "eslint-plugin-vue": "^9.3.0",
    "sass": "^1.70.0",
    "sass-loader": "^14.0.0",
    "vite": "^5.2.3",
    "vite-plugin-vuetify": "^2.0.3"
  }`

**Comment by RobSpectre** [comment]
This worked for me - thanks @coyotefather.

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify/commit/110985e30b32d031e5d45261ea90326c39b86c77

I don't know why you get the "no matching version" error, that would be a npm problem.
