### ISSUE TITLE
Missing component type definition

### ISSUE THREAD

**Issue by tbontb-iaq** [vuetifyjs/vuetify-loader#336]
## Problem

VSCode cannot obtain component type information.

## Steps to reproduce

1. Create a new project using `pnpm create vuetify` command
2. Choose "Recommended" preset, use Typescript and use pnpm
3. Install dependencies and use VSCode to open project

![image](https://github.com/user-attachments/assets/3115ecff-c8e0-43f9-b62c-e4ed3132eaac)

Run the `pnpm run dev` command and open the page in a browser to ensure that vite generates the corresponding type files.

Hover the mouse over the vuetify component and you can see that vscode cannot correctly identify their types.

![image](https://github.com/user-attachments/assets/8342c1fd-7f18-4b53-9dcb-81a04f12c3d3)

## Some information that may be useful

VSCode version: 1.91.1

Vue.volar: v2.0.26

**Comment by tbontb-iaq** [comment]
I found the complete type definitions in `node_modules/vuetify/lib/index.d.mts`, but I didn't know how to use them. I copied them into `vite-env.d.ts` and it worked fine.

![image](https://github.com/user-attachments/assets/52ef1af2-18a2-4485-8234-66b14a07db18)

**Comment by TianYa-Q** [comment]
You could do this

```
// vuetifyType.d.ts
declare module "vuetify/lib/framework" {
  import Vuetify from "vuetify";
  export default Vuetify;
}
```

**Comment by tbontb-iaq** [comment]
In fact they have fixed this in v3.6.13.

- typescript: augment GlobalComponents in multiple vue modules (https://github.com/vuetifyjs/vuetify/issues/20144) ([bd1f63d](https://github.com/vuetifyjs/vuetify/commit/bd1f63dcfc57ef0b15b8cfd2847bd40ba7751a39))

**Comment by KaelWD** [comment]
@tbontb-iaq please try the latest nightly build, we've changed this again: https://github.com/vuetifyjs/vuetify/commit/7c8aeefdc097ff9b74a733ed17b6a8cd9e1f8575
https://vuetifyjs.com/en/getting-started/installation/#nightly-builds

**Comment by tbontb-iaq** [comment]
No problems encountered. Test steps:

1. Create project with `pn create vuetify`
2. Install nightly with `pn i vuetify@npm:@vuetify/nightly@latest` and installed `@vuetify/nightly 3.7.0-master.2024-08-17`
3. Open the project with vscode, view HelloWorld component, and hover the mouse over the vuetify component to view the type definition

![image](https://github.com/user-attachments/assets/89c4f9c3-91d0-4ecd-9a14-8c391c79b5ee)
