### ISSUE TITLE
[Bug Report][vite-plugin-vuetify][2.0.4]  `WARN The CJS build of Vite's Node API is deprecated` after upgrade to version 2.0.4

### ISSUE THREAD

**Issue by guenbakku** [vuetifyjs/vuetify-loader#337]
## Environment
Vuetify Version: 3.7.0
Vue Version: 3.4.38
OS: Windows 10
vite-plugin-vuetify: 2.0.4

## Details
After upgraded vite-plugin-vuetify to latest version 2.0.4, there is deprecated warning in the command console: 
```
WARN  The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
```

**Comment by topd5** [comment]
I confirm.
Nuxt 3 + Vuetify:

![Screenshot_20240823_092306](https://github.com/user-attachments/assets/810d4bc6-392b-4c55-ab62-2d2ca15f6be4)

**Comment by KaelWD** [comment]
https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated
> ...make sure:
> - The vite.config.js file content is using the ESM syntax.
> - The closest package.json file has "type": "module", or use the .mjs/.mts extension, e.g. vite.config.mjs or vite.config.mts.
>
> If you're unsure where the warning is coming from, you can run your script with the VITE_CJS_TRACE=true flag to log the stack trace:

**Comment by Shiroe** [comment]
I also can confirm this on:
- `Nuxt@^3.13.0` 
- `vuetify@^3.7.1` 
- `vite-plugin-vuetify@^2.0.4`

Also the flag `VITE_CJS_TRACE=true` when used to run nuxt does not show the message anymore but nuxt is not 'a basic vite project' So none of the options there are working towards resolving this.

From the little I know and was able to look, i noticed that in the `package.json`
there are these two lines (5, 6)
```json
  "main": "./dist/index.cjs",
  "module": "./dist/index.mjs",
```

So if we look at the import line:
```ts
import vuetify, { transformAssetUrls } from 'vite-plugin-vuetify';
```

My guess is that in nuxt, in this instance (editing the nuxt.config.ts to add stuff inside the `vite` keyword), 
imports the `vite-plugin-vuetify` from the `.cjs` file rather than the `.mjs`.

Plus i was not able to adjust the import path to define it explicitly 

e.g.
```ts
import vuetify, { transformAssetUrls } from 'vite-plugin-vuetify/dist/index.mjs';
```

Hope you can find this helpful 🙏

**Comment by KaelWD** [comment]
> imports the vite-plugin-vuetify from the .cjs file rather than the .mjs

This would only happen if the file you're importing it from is also cjs.

**Comment by Shiroe** [comment]
> > imports the vite-plugin-vuetify from the .cjs file rather than the .mjs
> 
> This would only happen if the file you're importing it from is also cjs.
> 
> > there are these two lines (5, 6)
> 
> node 20 uses exports first https://github.com/vuetifyjs/vuetify-loader/blob/eed92c4149252fb0a426b7d3e5c2ccbed8a57e8c/packages/vite-plugin/package.json#L8-L13

Nuxt's configuration file (where the plugin is being imported) is usually a `.ts` and I also tried  converting it in a `.mts` but still had the same warning 😞

**Comment by KaelWD** [comment]
Unless VITE_CJS_TRACE is pointing you here it is most likely from nuxt itself or some other plugin.

**Comment by simon-lorenz** [comment]
I observe the same issue with a freshly initialized nuxt project. A downgrade to 2.0.3 solves it. Here's some output from `VITE_CJS_TRACE=true npm run dev`:

```text
 WARN  The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
 
    at warnCjsUsage (/path/to/project/node_modules/vite/index.cjs:50:11)
    at Object.<anonymous> (/path/to/project/node_modules/vite/index.cjs:1:1)
    at Object.<anonymous> (/path/to/project/node_modules/vite-plugin-vuetify/dist/index.cjs:6:14)
    at evalModule (/path/to/project/node_modules/jiti/dist/jiti.js:1:246482)
    at jiti (/path/to/project/node_modules/jiti/dist/jiti.js:1:245241)
    at /path/to/project/nuxt.config.ts:1:212
    at evalModule (/path/to/project/node_modules/jiti/dist/jiti.js:1:247313)
    at Object.jiti (/path/to/project/node_modules/jiti/dist/jiti.js:1:245241)
    at resolveConfig (file:///path/to/project/node_modules/c12/dist/shared/c12.cab0c9da.mjs:345:26)
    at loadConfig (file:///path/to/project/node_modules/c12/dist/shared/c12.cab0c9da.mjs:147:29)
    at async loadNuxtConfig (file:///path/to/project/node_modules/@nuxt/kit/dist/index.mjs:2597:18)
    at async Object.run (file:///path/to/project/node_modules/nuxi/dist/chunks/dev.mjs:171:25)
    at async runCommand$1 (file:///path/to/project/node_modules/nuxi/dist/shared/nuxi.fefc5017.mjs:1648:16)
    at async runCommand$1 (file:///path/to/project/node_modules/nuxi/dist/shared/nuxi.fefc5017.mjs:1639:11)
    at async runMain$1 (file:///path/to/project/node_modules/nuxi/dist/shared/nuxi.fefc5017.mjs:1777:7)
```

- `nuxt: 3.13.1`
- `vuetify: 3.7.1`
- `vite-plugin-vuetify: 2.0.4`
- `Node: 20.17.0`
- `NPM: 10.8.3`
- `OS: Ubuntu 22.04.3`

**Comment by KaelWD** [comment]
Do you have `"type": "module"` in package.json?

**Comment by KaelWD** [comment]
https://github.com/nuxt/nuxt/issues/27110
