### ISSUE TITLE
Compiled version is still using vuetify-loader

### ISSUE THREAD

**Issue by husayt** [vuetifyjs/vuetify-loader#34]
I get the following error when I try to run the bundle (created with nuxt) on the server with `nuxt-start`  
```
 (node_modules/vuetify-loader/lib/plugin.js:1) 
   Error: Cannot find module 'webpack/lib/RuleSet' 
```

Yes, I could simply include webpack to hide this issue. But the bundle has already been built, why  vuetify-loader is still being used?

**Comment by KaelWD** [comment]
Gonna need a repro please.
