### ISSUE TITLE
Browser DOMContentLoaded is too slow (20s+) when saving the variables.scss file

### ISSUE THREAD

**Issue by Yuban32** [vuetifyjs/vuetify-loader#342]
node version : v20.10.1
OS: Windows 10
Build Tool : vite 5.4.9
vite-plugin-vuetify version : 2.0.4

Browser DOMContentLoaded is too slow (20s+) when saving the variables.scss file
![Snipaste_2024-12-09_17-07-22](https://github.com/user-attachments/assets/e3267704-dcbd-49af-aa70-d8bba0a9e419)

Here is my config
``` js 
//vite.config.ts
export default defineConfig({
  plugins: [
    vue(),
    vuetify({
      styles:{
        configFile:'./src/assets/style/variables.scss'
      }
    })
  ],
  css: {
    preprocessorOptions: {
      sass: {
        api: 'modern-compiler', 
        silenceDeprecations: ["legacy-js-api"],
      }
    },
  },
});
```

``` scss
// variable.scss
@use 'vuetify/settings' with (
  $app-bar-background: #000000,
);

**Comment by Yuban32** [comment]
> Do you have sass-embedded installed?

In addition to vite-plugin-vuetify. do I need to install sass-embedded?
I followed the official tutorial to operate it.
The official tutorial does not mention this

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/features/sass-variables/#build-performance

**Comment by Yuban32** [comment]
> https://vuetifyjs.com/en/features/sass-variables/#build-performance
My fault. I ignored this.
I switch to the sass-embedded. now DOMContentLoaded is reduce to about 10s
thanks bro!
