### ISSUE TITLE
Cannot use a-la-carte method in testing

### ISSUE THREAD

**Issue by dchenk** [vuetifyjs/vuetify-loader#36]
I have this:
```
import Vuetify, {VSnackbar} from "vuetify/lib"
import "vuetify/src/stylus/app.styl"
```
and:
```
Vue.use(Vuetify, {
	components: {
		VSnackbar // Imported explicitly to be compiled for the vuetify-toast-snackbar library.
	},
	iconfont: "md",
	theme: {
		primary: "blue"
	}
})
```
This works when running the app and building it for production, but it fails when I use the Jest framework for testing. I see that there is [this issue](https://github.com/vuetifyjs/vue-cli-plugin-vuetify/issues/9), but the a-la-carte importing method is not used there.

My test file looks like:
```
import Vue from "vue"
import {shallowMount} from "@vue/test-utils"
import "@/plugins/vuetify" // This does: Vue.use(Vuetify, {...})
import {addVuetifyToast} from "@/plugins/vuetify-toast"
import App from "@/App.vue"

describe("App.vue", () => {
	addVuetifyToast(Vue)

	it("looks good", () => {
		const wrapper = shallowMount(App)
		expect(wrapper.text()).toEqual("...stuff...")
	})
})
```

I get a lot of these errors:
```
[Vue warn]: Unknown custom element: <v-list> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
    
    found in
    
    ---> <Anonymous>
           <Root>
```

I'm assuming that `vuetify-loader` should be used somehow to build the component. There isn't any documentation on how to do that.

**Comment by KaelWD** [comment]
We're already tracking an issue internally for better testing documentation, you need to import the entire library in your tests instead of `@/plugins/vuetify`

Have a test setup file that does
```js
import Vue from 'vue'
import Vuetify from 'vuetify'

Vue.use(Vuetify)
```

**Comment by valterbarros** [comment]
I put an empty array on jest.config.js option transformIgnorePatterns: [] and Work but only using Vue instance, not with localvue

**Comment by ClayShentrup** [comment]
So there's nothing I can do to hook into the same loading code I use in vue.config.js?

```javascript
  chainWebpack: (config) => {
    config
      .plugin('VuetifyLoaderPlugin')
      .tap(args => [{
        match(originalTag, {
          kebabTag, camelTag, path, component,
        }) {
          if (!camelTag.startsWith('Strata')) { return []; }
          return [camelTag, `import ${camelTag} from '@/components/${camelTag}.vue'`];
        },
      }]);
  },
```

**Comment by KaelWD** [comment]
Correct, jest doesn't use webpack or webpack plugins.
