### ISSUE TITLE
Webpack config for NUXTjs

### ISSUE THREAD

**Issue by ChibiChanNya** [vuetifyjs/vuetify-loader#37]
My project uses NUXT with the built in vuetify, but this doesn't seem to include the Progressive Images feature. I've installed this and added the VuetifyLoaderPlugin, but I can't figure out the rest.

Would anyone know what my nuxt.config.js should look like to get progressive images?

I do have ImageMagick.

**Comment by ejwaibel** [comment]
I was just trying to find something that would provide me with this solution as well!

I tried setting up the `build` configuration as explained:
```
extend(config, { isClient, loaders: { vue }}) {
      if (isClient) {
        vue.compilerOptions = vue.compilerOptions || {};
        vue.compilerOptions.modules = [VuetifyProgressiveModule];
        /*
          The following code will use the vuetify-loader/progressive-loader
          to automatically generate smaller images to load before loading the
          fullsize image.

          WARNING: You -MUST- have imagemagick installed for this to work
        */
        config.module.rules.push({
          test: /\.(png|jpe?g|gif|webp)(\?.*)?$/i,
          oneOf: [{
            test: /\.(png|jpe?g|gif)$/,
            resourceQuery: /vuetify-preload/,
            use: [
              'vuetify-loader/progressive-loader',
              {
                loader: 'url-loader',
                options: { limit: 8000 }
              }
            ]
          }, {
            loader: 'url-loader',
            options: { limit: 8000 }
          }]
        })
      }
    },
```
This seems to perform the transformation of images, but once the page loads, I get this error:
![vuetify-image-error](https://user-images.githubusercontent.com/2830686/56103096-c957b180-5ee5-11e9-8cf3-543a0b891747.png)

@ChibiChanNya perhaps you can change the title of this issue to *Webpack config with progressive-loader for nuxt project*

**Comment by KaelWD** [comment]
See #42, #12. You need to modify the existing rule so `url-loader` doesn't get applied twice. 

https://nuxtjs.org/api/configuration-build#loaders-in-extend

**Comment by ejwaibel** [comment]
@KaelWD yes, look at my example code and you'll see that I'm trying to do that, but not exactly sure how to do this with Nuxt? Based on documentation it seems like what I'm doing should be correct, but it's still failing.

**Comment by ejwaibel** [comment]
@KaelWD @ChibiChanNya this ended up being my solution:
```
// Need to tell webpack not to include images that are being
        // used with vuetify-preload with the url-loader
        config.module.rules
          .filter(v => v.test.toString().includes('png'))
          .map(v => v.exclude = /\.(png|jpe?g|gif)$/);

        /*
          The following code will use the vuetify-loader/progressive-loader
          to automatically generate base64 images to load before loading the
          fullsize image.

          WARNING: You -MUST- have imagemagick installed for this to work
        */
        config.module.rules.push({
          test: /\.(png|jpe?g|gif)$/,
          resourceQuery: /vuetify-preload/,
          use: [
            'vuetify-loader/progressive-loader',
            {
              loader: 'url-loader',
              options: { limit: 8000 }
            }
          ]
        });
```

**Comment by KaelWD** [comment]
In v1.4 you just need to pass `{ progressiveImages: true }` to the plugin constructor.

https://github.com/vuetifyjs/vuetify-loader/releases/tag/v1.4.0-beta.0
