### ISSUE TITLE
Unhandled promise rejections are deprecated

### ISSUE THREAD

**Issue by Akhail** [vuetifyjs/vuetify-loader#39]
![image](https://user-images.githubusercontent.com/22435967/51481531-751bb600-1d6a-11e9-8e24-4ae15587c691.png)
this happens when I have merger conflicts

**Comment by jn73** [comment]
I also run into this(?) problem. 'yarn serve' crashes if there is a syntax error in a pug-template - it won't recover and has to be restarted. When i roll back to "vuetify-loader": "1.0.6" it works again. Error is shown in browser and once fixed it renders the page ok.

**Comment by iuliuscaesar92** [comment]
@Akhail thank you for reporting this, I have the same problem. 
Is it gonna be fixed soon ?
