### ISSUE TITLE
using sharp instead of gm as image processor

### ISSUE THREAD

**Issue by ekoeryanto** [vuetifyjs/vuetify-loader#4]
Found my self struggling with `Error: Stream yields empty buffer` on windows 10.
I think it's better to use the more cross-platform image processor

Thanks.

**Comment by KaelWD** [comment]
Sharp doesn't support GIF output, so we'd have to use PNG or JPEG instead. I can certainly add an option to use a different processor, but the results will not be nearly as good. 
The error may be related to aheckmann/gm#559, I haven't actually tried gm on windows yet.

**Comment by ekoeryanto** [comment]
thinking about multi image processor support, maybe `vuetify-loader/sharp-loader.js`

I think aheckmann/gm#559 should be on the README.
installed with `scoop` that already appended all the binary of `imagemagick` not work, but installed manually with the `install legacy utilities` ticked works.
