### ISSUE TITLE
[Bug Report] A-la-carte web component using vue-cli-service 

### ISSUE THREAD

**Issue by dayre** [vuetifyjs/vuetify-loader#40]
### Versions and Environment
**Vuetify:** 1.4.3
**Vue:** 2.5.21
**Browsers:** Chrome 71.0.3578.98
**OS:** Mac OS 10.14.2

### Steps to reproduce
I'm trying to use the vuetify-loader plugin with the vue-cli-service to create a vuetify webcomponent.   The [vue-cli-service instructions say you just need to point it to the .vue file](https://cli.vuejs.org/guide/build-targets.html#web-component), but it's not clear from vuetify-loader or the vuetify a-la-carte instructions how to get this to work.

The only way i can get it to work is to explicitly import each component in the <script> tag AND each stylus file in the <style> tag.  

Simply importing app.styl in the <script> tag doesn't work.   Moving only app.style to the <style> tag only includes the basic .v-btn class, i need to also add each components .styl file to get the proper styling.

I've tried using the vuetify-loader, but can't get that to work with this use case and the documentation is lacking on how it might be able to be used in this example.

Could i get some clarification on how best to create a vueitfy based web-component using the vue-cli-service command ?   Should the vueitfy-loader work, if so how ?   Ideally it would be great to not have to import each component and stylus file manually when using the vue-cli-service command.   If there is no change to how this might be made easier for devs, it would be good to add some documentation to the a-la-carte section about this.  

I've included a repo with the example i got working where i had to explicitly import everything:
https://github.com/dayre/vuetify-loader-web-component

### Expected Behavior
Using vuetify-loader with vue-cli-service, NOT have to explicitly import each component AND component stylus file.

### Actual Behavior
Have to explicitly import each component and component stylus file.

### Reproduction Link
<a href="https://github.com/dayre/vuetify-loader-web-component" target="_blank">https://github.com/dayre/vuetify-loader-web-component</a>

**Comment by KaelWD** [comment]
See https://github.com/vuetifyjs/vuetify/issues/5054, web components are not currently supported.
