### ISSUE TITLE
Document how to configure `VuetifyProgressiveModule` with vue cli 3

### ISSUE THREAD

**Issue by acu192** [vuetifyjs/vuetify-loader#42]
The default vue cli 3.x projects use the so-called "no config" webpack. It's not clear to me (only me?) how to add `VuetifyProgressiveModule` to these vue cli 3.x projects.

Thank you for this library!

**Comment by KaelWD** [comment]
[It isn't pretty](https://github.com/vuetifyjs/vuetify-loader/issues/12#issuecomment-430675443)

**Comment by acu192** [comment]
Okay, here is my `vue.config.js` file now (very similar to the link you posted, but some differences):

```
const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin');
const { VuetifyProgressiveModule } = require('vuetify-loader');

module.exports = {
  chainWebpack:  config => {
    config.module
      .rule('vue')
      .use('vue-loader')
      .loader('vue-loader')
      .tap(options => {
        options.compilerOptions.modules = [VuetifyProgressiveModule];
        return options;
      });
    const imagesRule = config.module.rule('images');
    imagesRule.uses.clear();
    config.module
      .rule('images')
        .test(/\.(png|jpe?g|gif|webp)(\?.*)?$/)
        .oneOf('progressiveImages')
          .test(/\.(png|jpe?g|gif)$/)
          .resourceQuery(/vuetify-preload/)
          .use('progressiveLoader')
            .loader('vuetify-loader/progressive-loader')
            .end()
          .use('notProgressive')
            .loader('url-loader')
            .options({ limit: 8000, fallback: { loader: 'file-loader', options: { name: 'img/[name].[hash:8].[ext]' } } })
            .end();
    config.module
      .rule('images')
        .oneOf('imagesOther')
          .merge({ loader: 'url-loader', options: { limit: 8000, fallback: { loader: 'file-loader', options: { name: 'img/[name].[hash:8].[ext]' } } } });
  },
};
```

After writing that file, the first build attempt it complained that there was no `gm` module. I was happy to see it complain, as this indicated it was trying to do something new!  So, I `npm install gm --save`. (I have also already compiled and installed ImageMagick.)

After installing `gm`, it now _seems_ to work, at first glance. I.e. It builds without error.

However, when inspecting the `dist/` directory, I find that it hasn't modified my images at all. They are _identical_ to what is in my `src/assets/` folder.

On the vue side, here is the relevant code I'm using:
```
<v-img :src="require('@/assets/IMG_0219.jpg?vuetify-preload')">
```

Any ideas for why it's not generated progressive JPEGs?

**Comment by KaelWD** [comment]
It doesn't modify the output, check what the src prop is set to in vue-devtools.

**Comment by acu192** [comment]
Thank you @KaelWD. I see now how this works! Turns out the `vue.config.js` I posted above is working correctly. Thank you for the help!

**Comment by KaelWD** [comment]
In v1.4 you just need to pass `{ progressiveImages: true }` to the plugin constructor.

https://github.com/vuetifyjs/vuetify-loader/releases/tag/v1.4.0-beta.0

**Comment by austinbv** [comment]
@KaelWD There is still not a great example on how to enable this on a VueCLI project.

Where/how do you configure the loader plugin in the `vue.config.js`?

Thanks

**Comment by KaelWD** [comment]
```js
config.plugin('VuetifyLoaderPlugin').tap(args => [{
  // plugin arguments
}])
```

**Comment by boknoypatotoy** [comment]
modify `vue.config.js`

`module.exports = {
    transpileDependencies: ["vuetify"],`

    chainWebpack: (config) => {
        config.module
            .rule("vue")
            .use("vue-loader")
            .loader("vue-loader")
            .tap((options) => {
                options.transformAssetUrls = {
                    "v-img": "src",
                };

                return options;
            });
        config.plugin("VuetifyLoaderPlugin").tap((args) => [
            {
                progressiveImages: true,
            },
        ]);
    },
`};`

you should restart your server

`npm run serve`
