### ISSUE TITLE
I have rather odd situation regarding vuetify and vuetify loader plugin.

### ISSUE THREAD

**Issue by NevenD** [vuetifyjs/vuetify-loader#43]
I have rather odd situation regarding vuetify and vuetify loader plugin.

I posted problem on stackoverflow and Vue forum but without any luck so far. I've created simple SPA with implemented Vue and Vuetify and while in dev mode everything works fine I'm having problem in production mode. I'm getting rather strange error regarding my components

```
Uncaught TypeError: T(...)(...) is not a function
at Module.56d7 (VectorFeatures.vue:37)
at r (bootstrap:78)
at Object.0 (bootstrap:151)
at r (bootstrap:78)
at i (bootstrap:45)
at bootstrap:151
at bootstrap:151
```
Further inspecting error I'm getting this : 

[
![InkedScreenshot_1_LI](https://user-images.githubusercontent.com/26881459/54475844-b96d8480-47f6-11e9-8f36-e1d4770d8950.jpg)
](url)

My vue.config.js is this:

```
module.exports = {
    publicPath: process.env.NODE_ENV === 'production'
        ? '/hr-map/'
        : '/vue-map/',
    chainWebpack: config => {
        config.module
            .rule('vue')
            .use('vue-loader')
            .loader('vue-loader')
            .tap(options => {
                // modify the options...
                return options
            })
    }
}
```

And my router is this:
```
import Vue from 'vue'
import Router from 'vue-router'
import Dashboard from '@/views/Dashboard.vue'
import Croatia from '@/views/CroatiaMap.vue'
import Poland from '@/views/PolandMap.vue'

Vue.use(Router)

export default new Router({
  mode: 'history',
  base: process.env.BASE_URL,
  routes: [
    {
      path: '/',
      name: 'dashboard',
      component: Dashboard
    },
    {
      path: '/croatia',
      name: 'croatia',
      component: Croatia,
      meta: { keepAlive: true }
    },
    {
      path: '/poland',
      name: 'poland',
      component: Poland,
      meta: { keepAlive: true }
    }
  ]
})
```
Also worth mentioning is when I comment out lets say poland or croatia everything works fine on production

_Originally posted by @NevenD in https://github.com/vuetifyjs/vuetify-loader/issues/20#issuecomment-473529963_

**Comment by KaelWD** [comment]
If this is still a problem please create a basic project that can reproduce the issue.
