### ISSUE TITLE
Speed up webpack build by just importing the required components

### ISSUE THREAD

**Issue by jhnns** [vuetifyjs/vuetify-loader#44]
Hey 👋 

nice loader! 👍 

I think we could speed up the webpack build in smaller projects by only importing the required components instead of importing `vuetify/lib`. The latter will compile the whole vuetify library although only some of the components are actually used.

So instead of this:

```js
  import { VCard } from 'vuetify/lib'
```

I wish it did:

```js
  import { VCard } from 'vuetify/lib/components/VCard'
```

Do you think that would be possible? 😁

**Comment by KaelWD** [comment]
Just so it's in one place - to use this you have to change your main import to
```js
import Vuetify from 'vuetify/lib/framework'
```

**Comment by jacekkarczmarczyk** [comment]
There's no TS typing for `vuetify/lib/framework` though

**Comment by simonbrunel** [comment]
@jacekkarczmarczyk not sure if this has been mentioned/documented somewhere but as a workaround, I created `src/shims-vuetify.d.ts` (Vue CLI project) containing:

```ts
// src/shims-vuetify.d.ts
declare module 'vuetify/lib/framework' {
  import { Vuetify } from 'vuetify';
  const vuetify: Vuetify;
  export default vuetify;
}
```

That allows to import `vuetify/lib/framework` and set the `vuetify` instance to the `Vue` one:

```ts
// src/plugins/vuetify.ts
import Vuetify from 'vuetify/lib/framework';

Vue.use(Vuetify);

export default new Vuetify({
  // ...
});

// src/main.ts
import vuetify from './plugins/vuetify';

new Vue({
  vuetify,
  // ...
})
```

**Comment by jacekkarczmarczyk** [comment]
there's no more named export (https://github.com/vuetifyjs/vuetify/commit/3a0bd24bb19be055d94d00beddffa78f60a098bf#diff-da5869046c2bcfcdb989c88fb894e0738c3e6f02513ab783438167da4d8c36f3L23) so in 2.3.16+ this
```ts
declare module 'vuetify/lib/framework' {
  import { Vuetify } from 'vuetify';
  const vuetify: Vuetify;
  export default vuetify;
}
```

should be changed to

```ts
declare module 'vuetify/lib/framework' {
  import Vuetify from 'vuetify';
  const vuetify: Vuetify;
  export default vuetify;
}
```
