### ISSUE TITLE
Handling Duplicate Stylus in Build with vuetify-loader

### ISSUE THREAD

**Issue by uptownhr** [vuetifyjs/vuetify-loader#45]
When using the vuetify-loader while applying a custom stylus style entry, you are faced with a scenario where the final build off of webpack produces duplicate stylus packages. 

1. From the stylus/entry.stylus
2. From the vuetify/lib/component/.... -> calls `import component.stylus`

Not sure how to properly address this but one suggestion may to add an option into the Vuetify/lib components to disable the automatic stylus import.

Here's a github repo that I've created to dive into this issue. https://github.com/uptownhr/vuetify-loader-repo

**Comment by KaelWD** [comment]
Import `vuetify/src/stylus/app.styl`, not `vuetify/src/stylus/main.styl`: https://v15.vuetifyjs.com/en/framework/a-la-carte#required-styles

If you need to change variables use stylus-loader's `import` option.
