### ISSUE TITLE
vuetify-loader: not ignoring unknown top-level tags

### ISSUE THREAD

**Issue by NoahCardoza** [vuetifyjs/vuetify-loader#47]
After opening https://github.com/nuxt-community/router-extras-module/issues/15 we determined that, as the title states, `vuetify-loader` is not ignoring unknown top-level tags as per the Single-File Component spec.

I'm currently looking for a workaround.

**Comment by aldarund** [comment]
not vuetify loader problem in reality https://github.com/nuxt-community/router-extras-module/pull/44 
@KaelWD you can close this one :)
