### ISSUE TITLE
Compatibility With Laravel Mix?

### ISSUE THREAD

**Issue by codeitlikemiley** [vuetifyjs/vuetify-loader#49]
Hi ived tried many times, using it with laravel mix, but i keep getting error...
I understand this one is build to be used for vue-cli 3, yeah it works with nuxt also
but in case of laravel mix, how can use it on it, hope someone can help me with it thanks

**Comment by lukadriel7** [comment]
Hello, This implementation seems to work but weirdly I cannot read icon fonts with it (mdi).
I post here so that someone may improve on it.


```
const mix = require('laravel-mix');

mix.extend('vuetify', new class {
    webpackRules(){
        return [
            {
                type: 'javascript/auto',
                loader: 'vuetify-loader'
            }
        ]
    }
})

mix.vuetify().js('resources/js/app.js', 'public/js').sass('resources/sass/app.scss', 'public/css')
```

**Comment by codeitlikemiley** [comment]
let me check on it, and see how i can add the mdi icon fonts thanks for the share

**Comment by infernobass7** [comment]
@codeitlikemiley Did you get this working?

@lukadriel7 I get an issue `app.js Uncaught ReferenceError: component is not defined`

**Comment by codeitlikemiley** [comment]
I made a package
https://packagist.org/packages/codeitlikemiley/vuetified-laravel-preset
This work only because Dynamic components comes into play...
i dont even need to do The OP , cause it wont really work and faulty...
if u installed my package be sure to try it on fresh laravel install cause this is a preset.
also if u are using windows, make sure u use bash to run the command and have python installed inside your bash env.

**Comment by avengerweb** [comment]
Any updates?

**Comment by BenMstfa** [comment]
Any updates about this issue ?

**Comment by KaelWD** [comment]
See https://github.com/JeffreyWay/laravel-mix/issues/2173 and [my comment](https://discordapp.com/channels/340160225338195969/382204118435102730/608490081950629948) on discord

**Comment by leninsheikh** [comment]
use vuetify-loader in laravel mix like this

### webpack.config.js
```
const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin');
module.exports = {
    plugins: [
        new VuetifyLoaderPlugin(),
    ]
};
```
### webpack.mix.config
```
const mix = require('laravel-mix');
const webpack = require('./webpack.config');

mix.js('resources/frontend/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .webpackConfig(Object.assign(webpack));
```

**Comment by BraunLukas** [comment]
@leninsheikh 

trying to use your configuration, but it still give me some problems

`Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.`

when adding rules the js compiles, but im gettin JS errors on site loading
`[Vue warn]: Unknown custom element: <v-layout> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

**Comment by nekosaur** [comment]
You can compare your setup with this example project https://github.com/nekosaur/laravel-vuetify

**Comment by pintoflager** [comment]
@nekosaur 's example project is a working example as long as you don't update sass-loader. 
To be honest I'm just learning here and not 100% sure what's going on but if you do:
1. npm remove sass-loader
2. npm install sass-loader
3. npm run rev
Result is errors in vuetify main.scss file and fail in compile.

After npm install sass-loader@^7.1.0 -D I get following version installed in my package.json "sass-loader": "^7.3.1", and everything works fine again.

**Comment by beerwin** [comment]
> use vuetify-loader in laravel mix like this
> 
> ### webpack.config.js
> ```
> const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin');
> module.exports = {
>     plugins: [
>         new VuetifyLoaderPlugin(),
>     ]
> };
> ```
> 
> ### webpack.mix.config
> ```
> const mix = require('laravel-mix');
> const webpack = require('./webpack.config');
> 
> mix.js('resources/frontend/app.js', 'public/js')
>     .sass('resources/sass/app.scss', 'public/css')
>     .webpackConfig(Object.assign(webpack));
> ```

This should be put in the documentation. It just works.

**Comment by pintoflager** [comment]
No need for separate webpack.config.js 
Laravel mix seem to have .webpackConfig where you can add vuetifyloader
```
const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin');

mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .webpackConfig({
        plugins: [
            new VuetifyLoaderPlugin({
                options: {}
            }),
        ]
    })
    .version()
    .sourceMaps()
```

**Comment by jinxkitt108** [comment]
![error image load](https://user-images.githubusercontent.com/53928064/69477504-fbd56f80-0e21-11ea-8c14-6626a8b94005.png)
Im getting error in the console but image is loaded in the page, i want to know why

i followed this set up.

### **//Webpack.mix.js**

```
mix.js("resources/js/app.js", "public/js")
    .sass("resources/sass/app.scss", "public/css")
    .webpackConfig({
      resolve: {
         extensions: [".js", ".vue"],
         alias: {
             "@": __dirname + "/resources"
         }
     },
      plugins: [
          new VuetifyLoaderPlugin({
              options: {}
          }),
      ]
  })
  .version()
  .sourceMaps()
```

**Comment by tomcoonen** [comment]
I can't get the VuetifyLoaderPlugin to work, keep getting this error i.c.m. Laravel Mix:
`Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.`

Any ideas?

**Comment by DRoet** [comment]
@tomcoonen could you provide a small repro?

`cli 4.0.5` + `loader 1.4.2` works fine for me, so it could be related to your specific setup

**Comment by tomcoonen** [comment]
@DRoet I'm going to see if I can reproduce it in some way

**Comment by aubreychiduku** [comment]
> I can't get the VuetifyLoaderPlugin to work, keep getting this error i.c.m. Laravel Mix:
> `Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found. Make sure there is at least one root-level rule that uses vue-loader.`
> 
> I've tried the `mix.extend` but that gives me the same issues.
> 
> Vue CLI 3 / Laravel Mix 5.
> 
> Any ideas?

I'm having the same issue _without_ Vue CLI but using Laravel Mix 5 

where vuetify-loader 1.4.2 is included as a plugin using 

`.webpackConfig({
        plugins: [new VuetifyLoaderPlugin()]
    })
`

**Comment by KaelWD** [comment]
What version of vue-loader do you have?

**Comment by jinxkitt108** [comment]
I am using the vuetify-loader 1.4
Vuetify 2.0.17 and laravel 6. I use storage symlink. All my images are
saved in the storage folder. I have search all around 403 (Forbidden),
seems a permission issue. Do I need to change something in the htaccess, i
dont know.

**Comment by fraganzas** [comment]
Had the same issue when I updated to 1.4.2.
Running `npm install vuetify-loader@1.4.1` fixed it for me.

**Comment by jinseokoh** [comment]
the following works with Laravel Mix 5.0.0 and vuetify-loader 1.4.2 as opposed to none of above worked for me.

### webpack.config.js
```
const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin');

module.exports = {
    plugins: [
        new VuetifyLoaderPlugin({
            /**
             * This function will be called for every tag used in each vue component
             * It should return an array, the first element will be inserted into the
             * components array, the second should be a corresponding import
             *
             * originalTag - the tag as it was originally used in the template
             * kebabTag    - the tag normalised to kebab-case
             * camelTag    - the tag normalised to PascalCase
             * path        - a relative path to the current .vue file
             * component   - a parsed representation of the current component
             */
            match(originalTag, {kebabTag, camelTag, path, component}) {
                if (kebabTag.startsWith('core-')) {
                    return [camelTag, `import ${camelTag} from '@/components/core/${camelTag.substring(4)}.vue'`]
                }
            }
        }),
    ]
};
```
### webpack.mix.js
```
const mix = require('laravel-mix');

mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .webpackConfig({
        resolve: {
            modules: [
                "node_modules",
                path.resolve(__dirname, 'webpack.config')
            ]
        }
    });
```

**Comment by diorray** [comment]
After several hours of trying, i've made it working seamlessly.

First, don't use 1.4.2, install 1.4.1 by `npm install vuetify-loader@1.4.1`
Then, here is working solution

`const mix = require('laravel-mix');
const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin');

mix.options({
		extractVueStyles: true,
	}).webpackConfig({
		resolve: {
			extensions: ['.js', '.json', '.vue', '.css', '.scss', '.sass'],
			alias: {
				'~': path.join(__dirname, './resources/js'),
				'$comp': path.join(__dirname, './resources/js/components')
			}
		},
		module: {
			rules: [{
					test: /\.vue$/,
					loader: 'vue-loader',
				},
				{
					test: /\.js$/,
					loader: 'babel-loader',
					exclude: /node_modules\/(?!(vuetify)\/)/,
				},
				{
					test: /\.(sc|c|a)ss$/,
					use: [
						'vue-style-loader',
						'css-loader',
						{
							loader: 'sass-loader',
							options: {
								implementation: require('sass'),
								sassOptions: {
									fiber: require('fibers'),
									indentedSyntax: true
								},
							},
						},
					]
				},
			]
		},
		plugins: [
			new VuetifyLoaderPlugin()
		]
	}).js('resources/js/app.js', 'public/js/app.js')
	.css('resources/css/app.css', 'public/css/');`

Btw, you don't need to include vue-loader module as its already included in Laravel Mix, in fact if you try to do so, you will get the error below as you added module for the second time:

```
Error: [VueLoaderPlugin Error] No matching use for vue-loader is found.
Make sure the rule matching .vue files include vue-loader in its use.
```

**Comment by goldcoders** [comment]
@diorray  can you share you package.json file also i didnt manage to it work on my end
must be about the dependencies has mismatch packages

**Comment by diorray** [comment]
> @diorray can you share you package.json file also i didnt manage to it work on my end
> must be about the dependencies has mismatch packages

@goldcoders run this command:
`npm install mini-css-extract-plugin fibers deepmerge css-loader resolve-url-loader sass sass-loader style-loader stylus stylus-loader vue vue-loader@^15.7.2  vue-template-compiler vuetify-loader@1.4.1 vuetify"`

If still doesnt work, tell us details about the errors you facing on

**Comment by goldcoders** [comment]
im getting this error
```
ERROR in ./node_modules/vuetify/src/components/VDataTable/VDataTableHeader.sass (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src??ref--7-3!./node_modules/sass-loader/dist/cjs.js??ref--7-4!./node_modules/vuetify/src/components/VDataTable/VDataTableHeader.sass)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
ValidationError: Invalid options object. Sass Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'indentedSyntax'. These properties are valid:
   object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter? }
    at validate (/home/uriah/Sites/xxx/node_modules/sass-loader/node_modules/schema-utils/dist/validate.js:85:11)
    at Object.loader (/home/uriah/Sites/xxx/node_modules/sass-loader/dist/index.js:36:28)

```

**Comment by goldcoders** [comment]
Can you share a repo that has a minimimal install of vuetify working with vuetify loader 
that has all .babelrc webpack.mix.js app.js etc.
i find it hard to make it work on my end using your suggestions

**Comment by diorray** [comment]
> Can you share a repo that has a minimimal install of vuetify working with vuetify loader
> that has all .babelrc webpack.mix.js app.js etc.
> i find it hard to make it work on my end using your suggestions

@goldcoders you should remove node-sass, run this commmand and build again: `npm uninstall node-sass && npm install`

**Comment by SyncroIT** [comment]
> No need for separate webpack.config.js
> Laravel mix seem to have .webpackConfig where you can add vuetifyloader
> 
> ```
> const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin');
> 
> mix.js('resources/js/app.js', 'public/js')
>     .sass('resources/sass/app.scss', 'public/css')
>     .webpackConfig({
>         plugins: [
>             new VuetifyLoaderPlugin({
>                 options: {}
>             }),
>         ]
>     })
>     .version()
>     .sourceMaps()
> ```

I tried to do so but I always get this error when using vuetify-loader, it doesn't matter which version I use (I even tried the 1.4.1 instead of the 1.4.3).

> UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined

**Comment by Nothing-Works** [comment]
I create a [package](https://github.com/Nothing-Works/vuetifyjs-mix-extension). It does everything for you.

You can try it, and let me know if it's working for you.

And here is [laravel setup](https://github.com/Nothing-Works/vuetifyjs-mix-extension/blob/master/laravel.md)

**Comment by filipembcruz** [comment]
After many issues, I solve this on Laravel 8.

```
// Dependencies
{
        "laravel-mix": "^6.0.6",
        "sass": "^1.20.1",
        "sass-loader": "^8.0.0",
        "vue": "^2.5.17",
        "vue-loader": "^15.9.5",
        "vue-template-compiler": "^2.6.10",
        "vuetify": "^2.4.3",
        "vuetify-loader": "^1.7.1",
}
```

```
// webpack.mix.js
const mix = require('laravel-mix');
const webpack = require('./webpack.config');
Mix.listen('configReady', webpackConfig => {
    // scss
    const scssRule = webpackConfig.module.rules.find(
        rule =>
            String(rule.test) ===
            String(/\.scss$/)
    );
    scssRule.oneOf.forEach(o => {
        const scssOptions = o.use.find(l => l.loader === 'sass-loader').options
        scssOptions.prependData = '@import "./resources/sass/_variables.scss";'
    })

    // sass
    const sassRule = webpackConfig.module.rules.find(
        rule =>
            String(rule.test) ===
            String(/\.sass$/)
    );

    sassRule.oneOf.forEach(o => {
        const scssOptions = o.use.find(l => l.loader === 'sass-loader').options
        scssOptions.prependData = '@import "./resources/sass/_variables.scss"'
    })
})
mix.js('resources/js/app.js', 'public/js')
    .js('resources/js/gift.js', 'public/js')
    .vue()
    .sass('resources/sass/pages/home.scss', 'public/css')
    .sass('resources/sass/pages/gift.scss', 'public/css')
    .webpackConfig(Object.assign(webpack))
    .copyDirectory('resources/images/', 'public/images');

if (mix.inProduction()) {
    mix.version();
};
```
```
// webpack.config.js
const VuetifyLoaderPlugin = require('vuetify-loader/lib/plugin');
module.exports = {
    plugins: [
        new VuetifyLoaderPlugin(),
    ]
};
```

**Comment by JeffreyHosler** [comment]
@filipembcruz

I been working on this for like a month and kept telling myself i would come back later and fix it. This did the trick. thank you sir.

**Comment by JeffreyHosler** [comment]
actually @filipembcruz, do you happen to have a git i can look at? I am having issues with vuetify overwriting my custom css. Maybe its being loaded first or something. 

It is loading my variables which is nice. And my css is showing up in in console.log, just being over ridden by vuetify. 

```
// webpack.mix.js

Mix.listen('configReady', webpackConfig => {
    // scss
    const scssRule = webpackConfig.module.rules.find(
        rule =>
            String(rule.test) ===
            String(/\.scss$/)
	);
    scssRule.oneOf.forEach(o => {
        const scssOptions = o.use.find(l => l.loader === 'sass-loader').options
        scssOptions.additionalData = '@import "@/styles/variables.scss";'
    })

    // sass
    const sassRule = webpackConfig.module.rules.find(
        rule =>
            String(rule.test) ===
            String(/\.sass$/)
    );

    sassRule.oneOf.forEach(o => {
        const scssOptions = o.use.find(l => l.loader === 'sass-loader').options
        scssOptions.additionalData = '@import "@/styles/variables.scss"'
    })
})

mix.js('Resources/platform/src/main.js', path.resolve(__dirname, '../../public/assets/platform/js') )
	.vue()
	.webpackConfig({
		resolve: {
			alias: {
				'@webinar': path.resolve(__dirname, 'Resources'),
				'@assets': path.resolve(__dirname, 'Resources/platform/src/assets'),
				'@': path.resolve(__dirname, 'Resources/platform/src/'),
			}
		},
		output: {
			filename: '[name].js',
			path: path.resolve(__dirname, '../../public'),
			chunkFilename: mix.inProduction() ? 'assets/webinars/platform/js/[name].[chunkhash].js' : 'assets/webinars/platform/js/[name].js',
		},
		plugins: [
			new VuetifyLoaderPlugin(),
			new MomentLocalesPlugin({
				localesToKeep: ['el'],
			}),
		],
	})
	.sass('Resources/platform/src/styles/main.scss', path.resolve(__dirname, '../../public/assets/platform/css') )
```

```
// main.scss
@import 'variables';
@import 'mixins/breakpoints';
@import 'mixins/functions';
@import 'mixins/helpers';
@import 'mixins/mixins';
@import 'custom';

@import "components/header";
@import "components/form-ellements";
@import "components/login-form";
@import "components/sidebar";
@import "components/video-block";
@import "components/message-block";
@import "components/chat-block";
@import "components/faq-block";
@import "components/user-profile-box";
@import "components/empty-box";
@import "components/mobile-nav";
@import "components/overview-box";
@import "components/internet-users-popup";
@import "components/admin-panel";

.v-application {
  overflow: hidden;
  background: $primary-link-hover;
}

.header, .content{
  min-height: 100%;
  position: relative;
}
```

For example, this scss is howing up, but is getting over ridden by vuetifies scss
```
// components/login-form.scss
.login-form {
  .v-label {
    margin-bottom: 0;
    color: $primary-text-color;
    font-size: 14px;
    line-height: 1;
  }

  .v-btn__content {
    font-size: 15px;
    font-weight: 500;
  }

  a {
    &:hover {
      color:$primary-text-color;
    }
  }
}

```

**Comment by JeffreyHosler** [comment]
I fixed my issue by appending my custom css. like so

```
webpack.mix.js

Mix.listen('configReady', webpackConfig => {
    // scss
    const scssRule = webpackConfig.module.rules.find(
        rule =>
            String(rule.test) ===
            String(/\.scss$/)
    );
    scssRule.oneOf.forEach(o => {
        const scssOptions = o.use.find(l => l.loader === 'sass-loader').options
        scssOptions.additionalData = '@import "@/styles/main.scss";'
    })

    // sass
    const sassRule = webpackConfig.module.rules.find(
        rule =>
            String(rule.test) ===
            String(/\.sass$/)
    );

    sassRule.oneOf.forEach(o => {
        const scssOptions = o.use.find(l => l.loader === 'sass-loader').options
        scssOptions.additionalData = '@import "@/styles/main.scss"'
    })
})
```

```
// main.scss
@import 'variables';

.myCss {
}
```
