### ISSUE TITLE
Vue styleguidist inside Vue template

### ISSUE THREAD

**Issue by MaeseppTarvo** [vuetifyjs/vuetify-loader#55]
Hey! Awesome plugin. Just wanted to ask, is it possible to use vue-styleguidist inside template and keep vuetify-loader working?

I am getting the following error: ```Uncaught TypeError: "" is not a function``` if vuetify-loader is enabled and if my .vue file contains the following which is required to have example in vue-styleguidist documentation:

```
<docs>
```vue
  <template>
  </template>
```
</docs>

**Comment by KaelWD** [comment]
Duplicate of #47
