### ISSUE TITLE
[Getting started]: using css loaders to import vuetify minified css

### ISSUE THREAD

**Issue by coder9604** [vuetifyjs/vuetify-loader#59]
I'm new to vuetify.js and was following the instructions as in the docs to set up vuetify within my vue.js based web app. 

These were the steps followed:-
- Installed the `vuetify` package
- Configured `src/main.js` respectively:- (added these 3 lines)
     - `import Vuetify from 'vuetify';`
     - `Vue.use(Vuetify);`
     - `import 'vuetify/dist/vuetify.min.css'`

I made out a component and filled it with:-
```html
<template>
  <v-btn color="success"></v-btn>
</template>
```
But the button wasn'tget rendered in the intended way. I'm confused by this instruction:- Ensure you are using css-loader

I installed `css-loader` as a dev-dependency still, nothing seems to change. 

What am I doing wrong? Any help would be appreciated :clap:

**Comment by coder9604** [comment]
cc @johnleider @adamdyson @nekosaur @KaelWD

**Comment by coder9604** [comment]
cc @johnleider @nekosaur @KaelWD

**Comment by jacekkarczmarczyk** [comment]
https://vuetifyjs.com/en/getting-started/quick-start

The issue list of this repo is **exclusively** for bug reports and feature requests. For general questions, please join [the Discord chat room](https://community.vuetifyjs.com). You can also check [reddit](https://www.reddit.com/r/vuetifyjs/) or [stackoverflow](https://stackoverflow.com/questions/tagged/vuetify.js).
