### ISSUE TITLE
[Bug Report] Duplicated vue-theme-stylesheet dom node

### ISSUE THREAD

**Issue by jousepo** [vuetifyjs/vuetify-loader#61]
### Environment
**Vuetify Version:** 2.0.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 75.0.3770.142
**OS:** Linux x86_64

### Steps to reproduce
-Configure vuetify with nuxt and init server
-Load initial page and see HEAD in DOM

### Expected Behavior
Only one stylesheet in dom.
When change primary color in theme using javascript must be changed.

### Actual Behavior
Two stylesheets in dom.
When change primary color using javascrip only first stylesheet is updated and nothing change in web

### Reproduction Link
<a href="" target="_blank"></a>

### Other comments
I've commented the problem in the previous fix thread: 
https://github.com/vuetifyjs/vuetify/pull/7443

**Comment by KaelWD** [comment]
This isn't related to vuetify-loader
