### ISSUE TITLE
Custom styles aren't loaded anymore starting with 1.3.0

### ISSUE THREAD

**Issue by bromix** [vuetifyjs/vuetify-loader#62]
We updated to vuetify 2.0.1 and also got an update for vuetify-loader 1.3.0. We followed the guide for [customizing the styles](https://vuetifyjs.com/en/customization/sass-variables) (scss/sass) and everything worked so far.

But as soon as we update to v1.3.0 of vuetify-loader the styles are gone/not imported.

We import the styles via a rule in a webpack.config:
```javascript
rules: [
      {
        test: /\.sass$/,
        use: [
          "style-loader",
          "css-loader",
          {
            loader: "sass-loader",
            options: {
              data: `@import '@styles/main.scss'`,
              implementation: require("sass"),
              fiber: require("fibers"),
              indentedSyntax: true // optional
            }
          }
        ]
      },
```
If you need any more information, please let me know.

**Comment by KaelWD** [comment]
This is very likely not related to vuetify-loader, it doesn't touch anything to do with sass. You may have updated other packages at the same time.
