### ISSUE TITLE
[Bug Report] Base CSS styles aren't loaded by vuetify-loader 1.3.0

### ISSUE THREAD

**Issue by brokenthorn** [vuetifyjs/vuetify-loader#69]
### Environment

**Browsers:** Firefox 69.0
**OS:** Mac OS 10.14

### Steps to reproduce
Most helpful tertiary issue I found that helped me solve this problems is [this](https://github.com/nuxt-community/vuetify-module/issues/13).

The steps to reproduce are quite hard to describe.
I upgraded a small vue-cli 3 + vue-cli-plugin-vuetify 0.6.1 project from Vuetify v.1 to v.2 basically and everything went OK, except for base styles not being loaded.

It seems to fix itself by adding line 4:

```ts
import Vue from "vue";

import Vuetify from "vuetify";
import "vuetify/dist/vuetify.min.css";
import en from "vuetify/src/locale/en";
import ro from "vuetify/src/locale/ro";
import {VuetifyPreset} from "vuetify/types/presets";

Vue.use(Vuetify);

const preset: VuetifyPreset = {
  theme: {
    dark: false
  },
  locale: {
    locales: {ro, en},
    current: "ro"
  },
  icons: {
    iconfont: "mdiSvg"
  }
};

export default new Vuetify(preset);
```

But that isn't specified in the Quick Start guide @ [#vuetify-loader-installation](https://next.vuetifyjs.com/en/getting-started/quick-start#vuetify-loader-installation), but is specified @ [#full-installation](https://next.vuetifyjs.com/en/getting-started/quick-start#full-installation).

### Expected Behavior
vuetify-loader should load all required CSS

### Actual Behavior
vuetify-loader doesn't load base CSS styles

### Reproduction Link
<a href="" target="_blank"></a>

**Comment by KaelWD** [comment]
You're importing the UMD build, vuetify-loader has no effect.

**Comment by asilhome** [comment]
Hi,

I'm having this issue https://github.com/vuetifyjs/vuetify/issues/7978.

Then when I added this line mentioned by OP, @brokenthorn :

```
// vuetify.js, vuetify: 2.0.7, vuetify-loader: 1.3.0

...
import "vuetify/dist/vuetify.min.css";
```

it works!
