### ISSUE TITLE
[Bug Report] Vuetify loader doesn't load components listed in external libraries

### ISSUE THREAD

**Issue by tclindner** [vuetifyjs/vuetify-loader#70]
### Environment

**Browsers:** Google Chrome, Safari 12.1.2, Safari, Mozilla Firefox
**OS:** Mac OS 10.14.6

### Steps to reproduce
Reference a library such as `vuetify-daterange-picker` or another library that wraps Vuetify components. 

In the `main.js` file add.

```js
import Vue from 'vue';
import App from './App.vue';
import VuetifyDaterangePicker from "vuetify-daterange-picker";
import "vuetify-daterange-picker/dist/vuetify-daterange-picker.css";
import vuetify from './plugins/vuetify';

Vue.use(VuetifyDaterangePicker);

new Vue({
  vuetify,
  render: h => h(App)
}).$mount('#app');
```

In `./plugins/vuetify` add

```js
import Vue from 'vue';
import Vuetify from 'vuetify/lib';

Vue.use(Vuetify);

export default new Vuetify({
  icons: {
    iconfont: 'mdi'
  }
});
```

Implement the component like

```js
<template>
  <v-daterange v-model="range"></v-daterange>
</template>
```

### Expected Behavior
`VAppBar` and `VToolbarTitle` are loaded in a la carte mode. 

### Actual Behavior
The following error is generated in this scenario.

`Unknown custom element: <v-list> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
found in
---> <VDaterange>`

### Reproduction Link
<a href="" target="_blank"></a>

### Other comments
The module currently uses `configureWebpack` to list that `vuetify/lib` as external.

```js
module.exports = {
  configureWebpack: {
    ...(process.env.NODE_ENV === 'production'
      ? {
          externals: {
            'vuetify/lib': 'vuetify/lib',
            'date-fns': 'date-fns'
          }
        }
      : {})
  }
};
```

To work around the error you can skip a la carte mode and import `import Vuetify from 'vuetify'`, but this is less than ideal since you lose tree shaking. 

Is there an alternative way to implement and meet the following criteria:

* Wrapping module doesn't depend on `vuetify` (Peer dep only)
* Consuming app can using a la carte mode and get all of the benefits of tree shaking
* Consuming app doesn't need to import any of the peer dependencies of the wrapping module. 

Thank you so much in advance! I appreciate all of the great work you've put in to Vuetify. 
Please let me know if you need additional information.

**Comment by morficus** [comment]
+1

I think this is less of a bug report and more of a feature request.
It would be great if the vuetify-loader could find and auto-import Vuetify components that are in 3rd party modules (like mentioned above, those that use Vuetify as a peer dependency).

**Comment by KaelWD** [comment]
Not possible. They're distributing a compiled component so we can't parse the template to determine what they're using. 

Either:
 - Import the other library from src so your vue-loader is run on it.
 - Globally register the components it uses.
 - Tell the library author to add imports for all the vuetify components in use.

**Comment by morficus** [comment]
@KaelWD question about option 3, if the library author was to add imports for all vuetify components (aka: local registration), would there be a chance of some components getting included twice in to a production build?

ie: 3rd party lib uses v-btn which gets included in its build, main application also uses v-btn. Would be final output include two compiled definitions for v-btn? or would webpack somehow magically handle this case?

**Comment by KaelWD** [comment]
Only in the case of something like https://github.com/vuetifyjs/vuetify/issues/4068

**Comment by iliyaZelenko** [comment]
@KaelWD I used the third method. 

> Tell the library author to add imports for all the vuetify components in use.

More precisely, I am the author of the library. And the library worked fine, except that it caused an error on the server-side rendering (https://github.com/iliyaZelenko/tiptap-vuetify/issues/60).

I imported from `'vuetify/lib'`, for example:

```js
import { VBtn } from 'vuetify/lib'
```

After the build in CommonJS bundle (CJS modules), ES imports converted to CJS, this code above at the runtime accessed the `'vuetify/lib'` files, but they had ES modules, which led to an error in the CJS context.

I don’t know what to do now, I don’t want the component to not support SSR and I also need support for tree shaking.

> Globally register the components it uses.

Exit, but not the best option. Any ideas? It will help a lot.

**Comment by MikeMitterer** [comment]
@KaelWD I have the same problem. In my lib I try to import VBtn explicitly 

```typescript
<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';
import { VBtn } from 'vuetify/lib';

// import { VBtn } from 'vuetify/lib';

@Component({ name: 'MLiveForce', components: { VBtn: VBtn } })
export default class MLiveForce extends Vue {
    // private readonly logger = loggerFactory.getLogger('<package>');

    @Prop({ default: false })
    private myProp!: boolean;

    private status: boolean = this.myProp;

    private onClick(): void {
        this.status = !this.status;
    }
}
// export default { comments: { VBtn } };
</script>
```

But this leads to (If I build with rollup)

```bash
[!] Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
node_modules/vuetify/src/styles/main.sass (3:0)
1: // Modeled after ITCSS https://www.xfive.co/blog/itcss-scalable-maintainable-css-architecture/
2:
3: @import './tools/_index'
   ^
4: @import './settings/_index'
5: @import './generic/_index'
Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
```

Any ideas?

**Comment by KaelWD** [comment]
Add vuetify to whatever rollup's version of externals is.

**Comment by MikeMitterer** [comment]
OMG!!! @KaelWD after two days f... with this problem, this brought the solution! THANKS.
It was not just vuetify but also vuetify/lib

To others with the same problem - here are the main changes I had to made

```javascript
<template>
    <div>
        LiveForce! Prop:
        <span class="prop" :class="{ active: status }">{{ status }}</span>
        <v-btn text small color="primary" @click="onClick">Click me!</v-btn>
    </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

// Import VBtn - I'm using v-btn in the template
import { VBtn } from 'vuetify/lib';

// Adding VBtn to components
@Component({ name: 'MLiveForce', components: { VBtn } })
export default class MLiveForce extends Vue {
    @Prop({ default: false })
    private myProp!: boolean;

    private status: boolean = this.myProp;

    private onClick(): void {
        this.status = !this.status;
    }
}
</script>
```

In rollup.config.js:
```json
export default {
    external: [
        ...Object.keys(pkg.dependencies || {}),
        "tslib",
        "vue",
        // "vue-class-component",
        // "vue-property-decorator",
        "vuex",
        "vuex-class",
        "vuetify",
        "vuetify/lib"
    ],
}
```

**Comment by MikeMitterer** [comment]
I wonder why this issue is marked as "solved" - this is a problem a bugs people...

**Comment by VitaliyDemchuk** [comment]
> OMG!!! @KaelWD after two days f... with this problem, this brought the solution! THANKS.
> It was not just vuetify but also vuetify/lib
> 
> To others with the same problem - here are the main changes I had to made
> 
> ```js
> <template>
>     <div>
>         LiveForce! Prop:
>         <span class="prop" :class="{ active: status }">{{ status }}</span>
>         <v-btn text small color="primary" @click="onClick">Click me!</v-btn>
>     </div>
> </template>
> 
> <script lang="ts">
> import { Component, Prop, Vue } from 'vue-property-decorator';
> 
> // Import VBtn - I'm using v-btn in the template
> import { VBtn } from 'vuetify/lib';
> 
> // Adding VBtn to components
> @Component({ name: 'MLiveForce', components: { VBtn } })
> export default class MLiveForce extends Vue {
>     @Prop({ default: false })
>     private myProp!: boolean;
> 
>     private status: boolean = this.myProp;
> 
>     private onClick(): void {
>         this.status = !this.status;
>     }
> }
> </script>
> ```
> 
> In rollup.config.js:
> 
> ```json
> export default {
>     external: [
>         ...Object.keys(pkg.dependencies || {}),
>         "tslib",
>         "vue",
>         // "vue-class-component",
>         // "vue-property-decorator",
>         "vuex",
>         "vuex-class",
>         "vuetify",
>         "vuetify/lib"
>     ],
> }
> ```

Cannot read property 'VBtn' of undefined. What happened?

**Comment by chaim0m** [comment]
I am still getting errors of `Unknown custom element: <v-btn> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`
Even after trying all the solutions here and more.   
I import the components explicitly in the library code and then make them global in the consumer. Nothing, any help appreciated. This problem never existed before the upgrade to v2

**Comment by MikeMitterer** [comment]
Made a Screenshot - shows what I'm working on. (Have you seen my TS-Component-Template: https://github.com/MikeMitterer/vue-ts-sfc-starter/blob/master/src/index.ts)

On the left side is the index.ts of my component lib on the right side you can see how I integrate the lib
One of the few things bugged me was the way I imported the components (left side): I had to use the "relative-path-way" to import e.g. MJob (TS-path did not work)

![Bildschirmfoto 2020-02-12 um 15 49 57](https://user-images.githubusercontent.com/116654/74346091-580bb800-4daf-11ea-9c7b-a4512abe9aad.png)

**Comment by chaim0m** [comment]
> Made a Screenshot - shows what I'm working on. (Have you seen my TS-Component-Template: https://github.com/MikeMitterer/vue-ts-sfc-starter/blob/master/src/index.ts)
> 
> On the left side is the index.ts of my component lib on the right side you can see how I integrate the lib
> One of the few things bugged me was the way I imported the components (left side): I had to use the "relative-path-way" to import e.g. MJob (TS-path did not work)
> 
> ![Bildschirmfoto 2020-02-12 um 15 49 57](https://user-images.githubusercontent.com/116654/74346091-580bb800-4daf-11ea-9c7b-a4512abe9aad.png)

Thank you! What are you exporting in the library? I see the major difference is that you are using `Vue.use(myComps)` which I will try now.

**Comment by MikeMitterer** [comment]
Huuu... 
here are the missing two lines:
```typescript
// This should not be necessary
export { MDevice, MLiveForce, MJob, MJobEdit, MLocationEdit, MMediaEdit, MDateEdit, MTimeEdit };
// This thing counts!
export default MobiAdComponents;
```

**Comment by chaim0m** [comment]
> Huuu...
> here are the missing two lines:
> 
> ```ts
> // This should not be necessary
> export { MDevice, MLiveForce, MJob, MJobEdit, MLocationEdit, MMediaEdit, MDateEdit, MTimeEdit };
> // This thing counts!
> export default MobiAdComponents;
> ```
> 
> [Update]
> Did you see (vuetify.ts) (lower right corner in SS)
> 
> ```ts
> Vue.use(Vuetify, {
>     components: { VTextField, VMenu, VDatePicker, VTimePicker },
> });
> ```

Ok so I now reached a point where there are no erros but sadly even though I can see the component in the devtools it is not rendering. Any suggestions?

**Comment by chaim0m** [comment]
Setup of the library:
`import Vue from 'vue';

import Logout from './components/Logout';

import Apps from './components/Apps';

import Toast from './components/Toast';

import { securityServiceFactory } from "./security/index";
import { Services } from "./services";
import { Utils } from "./utils";

const Security = {
    ServiceFactory: securityServiceFactory
};

 export function install(Vue) {
    if (install.installed) return;
    install.installed = true;
    Vue.component('Logout', Logout);
    Vue.component("Apps", Apps);
    Vue.component("Toast", Toast);
}

// Create module definition for Vue.use()
const common = {
    install,
};

// Auto-install when vue is found (eg. in browser via <script> tag)
if (typeof window !== 'undefined' && window.Vue){
    window.Vue.use(common)
}
export {
    common,
    Security,
    Services,
    Utils
} 
// in the vue.config.js
module.exports = {
    configureWebpack: {
        // output: {
        //     libraryExport: 'default'
        // }
        externals: {
            vuetify: '$vuetify',
            'vuetify/lib': 'vuetify/lib',
            'vue':'vue',
            vue:'vue'
        }
    }
};
`
main.js in consumer app:
`import  {common}  from "em-common-vue"
import {Services, Security, Utils} from 'em-common-vue';
Vue.use(common)
....
// in the "Header" component:
..
      <Logout :key="someKey" color="primary--text" :appsService="appsService"></Logout>
...
// vueitfy.js
...
Vue.use(Vuetify, {
    components: {VTooltip, VBtn, VIcon, VMenu, VContainer, VRow, VCol, VCard, VCardText, VAvatar, VSnackbar}
})
`
End result is, it's all there but nothing showing, any help greatly appreciated !

**Comment by MikeMitterer** [comment]
I can see you are using webpack - forget it. I never had a chance to make it work with WP. After fiddling for days with WP I switched to rollup for the component lib and this did the trick.

**Comment by khoathanglong** [comment]
Did anyone mange to make it work with webpack?
