### ISSUE TITLE
[Bug Report] Al la carte don't work on functional components

### ISSUE THREAD

**Issue by Mnwa** [vuetifyjs/vuetify-loader#71]
### Environment

**Browsers:** Chrome 75.0.3770.142
**OS:** Mac OS 10.14.6

### Steps to reproduce
Clone https://github.com/Mnwa/vuetify-bug 
Install deps
Run serve

### Expected Behavior
We'll see beautiful card with title "Test"

### Actual Behavior
Vuetify components don't parsed

**Comment by jacekkarczmarczyk** [comment]
https://vuetifyjs.com/en/customization/a-la-carte#functional-components
