### ISSUE TITLE
Module parse failed: Unexpected character '@'

### ISSUE THREAD

**Issue by codesigner-io** [vuetifyjs/vuetify-loader#74]
After I add the vuetify-loader to my webpack.config.js

ERROR in ./node_modules/vuetify/src/components/VCard/VCard.sass 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
> @import '../../styles/styles.sass'
| 
| // Theme
ERROR in ./node_modules/vuetify/src/directives/ripple/VRipple.sass 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
> @import '../../styles/styles.sass'
| @import './_variables.scss'
| 
ERROR in ./node_modules/vuetify/src/components/VProgressLinear/VProgressLinear.sass 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
> @import '../../styles/styles.sass'
| @import './_variables.scss'
| 
ERROR in ./node_modules/vuetify/src/components/VSheet/VSheet.sass 2:0
Module parse failed: Unexpected character '@' (2:0)
You may need an appropriate loader to handle this file type.
| // Imports
> @import '../../styles/styles.sass'
| @import './_variables.scss'
|

**Comment by KaelWD** [comment]
you need sass-loader.

**Comment by nscozzaro** [comment]
@KaelWD I also have this issue, and have installed sass-loader. 

![image](https://user-images.githubusercontent.com/15185105/63376363-a63d8280-c35b-11e9-9d5e-943a6941114d.png)

![image](https://user-images.githubusercontent.com/15185105/63376407-bbb2ac80-c35b-11e9-9e1e-2ae476ebef7d.png)

Please let me know what else might be the issue, thanks!

**Comment by nekosaur** [comment]
Your rule test only includes scss files. Change it to `/\.s(c|a)ss$/`

**Comment by Shuyinsama** [comment]
I still get this error when I try to load Vuetify in a-la-carte.

I copied the rules from the website for sass-loader ~7.0.0 (I am using 7.3.1)

```js
{
    test: /\.s(c|a)ss$/,
    use: [
        'vue-style-loader',
        'css-loader',
        {
            loader: 'sass-loader',
	    options: {
	        implementation: require('sass'),
                fiber: require('fibers'),
	        // optional
                indentedSyntax: true
            }
        }
    ]
}
```

and my Vuetify import

```js
import Vue from 'vue';
import Vuetify from 'vuetify/lib';
import VueI18n from 'vue-i18n';
import VueCroppie from 'vue-croppie';

Vue.use(VueCroppie);
Vue.use(Vuetify);
```

yet I still get this error

```
ERROR in ./node_modules/vuetify/src/components/VTimeline/VTimeline.sass 2:0
    Module parse failed: Unexpected character '@' (2:0)
    You may need an appropriate loader to handle this file type.
    | // Imports
    > @import '../../styles/styles.sass'
    | @import './_variables.scss'
    | @import './_mixins.sass'
     @ ./node_modules/vuetify/lib/components/VTimeline/VTimeline.js 2:0-58
     @ ./node_modules/vuetify/lib/components/VTimeline/index.js
     @ ./node_modules/vuetify/lib/components/index.js
     @ ./node_modules/vuetify/lib/index.js
     @ ./src/main/resources/static/js/source/vendors/vue-and-vuetify.js
```

**Comment by nscozzaro** [comment]
Same here, I just didn't get around to responding until now.

**Comment by devsuitup** [comment]
Same here !

**Comment by zim32** [comment]
> Your rule test only includes scss files. Change it to `/\.s(c|a)ss$/`

And this rule. What does it match?  Does it match CSS? If no why should we import ''vuetify/dist/vuetify.min.css' according to documentation?

**Comment by HudaSarkawt** [comment]
only install **@storybook/preset-scss**   `https://www.npmjs.com/package/@storybook/preset-scss` , then import it into **main.js** 

> module.exports = {
>   stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.js'],
>   addons: [
>     '@storybook/preset-typescript',
>     '@storybook/preset-scss',
>     '@storybook/addon-links',
>     '@storybook/addon-essentials',
>     '@socheatsok78/storybook-addon-vuetify',
>   ],
>   framework: '@storybook/vue',
> }
