### ISSUE TITLE
[Bug Report] Duplicate CSS generated in A-la-carte mode for SASS 

### ISSUE THREAD

**Issue by kumaravnish** [vuetifyjs/vuetify-loader#80]
### Environment

**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
I followed the directions in https://vuetifyjs.com/en/customization/sass-variables to setup A-la-carte mode compilation of SCSS with some variable overrides as well as my project related custom SCSS files. 

When looking at the output of the build, the CSS seems to be duplicated multiple times for each css bundle, and multiple times in the same bundle file as well. It seems like my project customizations are being appended to each Vuetify component/file. 

Could it be related to 
```
["vue-modules", "vue", "normal-modules", "normal"].forEach(match => {
  config.module
    .rule("scss")
    .oneOf(match)
    .use("sass-loader")
    .tap(opt =>
      Object.assign(opt, { data: `@import '~@/styles/main.scss';` })
    );
});
```

### Expected Behavior
CSS is not duplicated in the bundle

### Actual Behavior
CSS is duplicated

### Reproduction Link
<a href="" target="_blank"></a>

**Comment by nekosaur** [comment]
The `styles/main.scss` file should only include variables (and mixins, etc). It should contain no actual styles. Because as you said, the file gets prepended to each existing import.

Your actual custom styles should live in a separate file that you import for example in your `main.js` file.

**Comment by kumaravnish** [comment]
@nekosaur 
Thanks for that reply. I wish it was documented better.

**Comment by jcupps** [comment]
I was also getting a ton of duplication despite adding any styles or imports to `main.scss` or `settings.scss`, just `@use vuetify` and variable overrides.

I was able to resolve the duplication by changing the name of the `main.scss` file.
