### ISSUE TITLE
[Bug Report] Conflict order warning for sass files

### ISSUE THREAD

**Issue by mynormeza** [vuetifyjs/vuetify-loader#81]
### Environment

**Browsers:** Chrome 76.0.3809.100
**OS:** Windows 10

### Steps to reproduce
I'm receiving the following warning when creating production build with webpack.

```
WARNING in chunk npm.vuetify [mini-css-extract-plugin]
Conflicting order between:
 * css ./node_modules/css-loader/dist/cjs.js??ref--4-1!./node_modules/sass-loader/dist/cjs.js??ref--4-2!./node_modules/vuetify/src/components/VInput/VInput.sass
 * css ./node_modules/css-loader/dist/cjs.js??ref--4-1!./node_modules/sass-loader/dist/cjs.js??ref--4-2!./node_modules/vuetify/src/components/VPagination/VPagination.sass
 * css ./node_modules/css-loader/dist/cjs.js??ref--4-1!./node_modules/sass-loader/dist/cjs.js??ref--4-2!./node_modules/vuetify/src/components/VMenu/VMenu.sass
```

I'm using vuetify loader and everything works fine except when using webpack dynamic import, I'm kind of newbie but as soon as I comment my webpack dynamic imports the warning disapears that's why I believe this may be a bug when using dynamic improts. If I use full installation of vuetify no warnings show up.

This happens with many vuetify controls. The following is a snippet of my dynamic import, there no spacial science in it.

```
computed: {
        loader (){
            if (!this.dType) {
                return null;
            }
            return () => import(`@/components/login/${this.dType}`);
        }
    }
```

### Expected Behavior
No warnings

### Actual Behavior
Shows warnings

### Reproduction Link
<a href="" target="_blank"></a>

**Comment by KaelWD** [comment]
See https://github.com/vuetifyjs/vuetify/issues/5271#issuecomment-434688989
