### ISSUE TITLE
How to disable the generation of unneeded breakpoints and theme colors?

### ISSUE THREAD

**Issue by geekox86** [vuetifyjs/vuetify-loader#84]
Greetings all,

The generated css file is over 200K. I am using vuetify-loader-plugin with webpack 4.

How to disable the generation of unneeded breakpoints and theme colors?

Regards

**Comment by KaelWD** [comment]
https://vuetifyjs.com/en/customization/sass-variables

The breakpoints gzip pretty well anyway so it only looks big.

**Comment by geekox86** [comment]
@KaelWD what sass-variables have todo with reducing the size of the generated css?

90% of the generated css is unneeded and I have to make space for other libraries.

Is there a way to disable the generation of unneeded breakpoints and theme colors?

**Comment by KaelWD** [comment]
Yes, here's one where I've disabled all the utility classes: https://github.com/vuetifyjs/vuetify-loader/blob/master/dev/src/_variables.scss

**Comment by IvoPereira** [comment]
Hi @KaelWD,

I was looking to reduce the bundle size as well. I have tried to follow the repo you linked but it does not seem to be available anymore.

Perhaps you could link me to a new one?

**Comment by KaelWD** [comment]
https://github.com/vuetifyjs/vuetify-loader/blob/4de3c946f329bcce3548a0aa753b34672818bdc0/dev4/src/_variables.scss
