### ISSUE TITLE
Please add the LICENSE file

### ISSUE THREAD

**Issue by dpipchenko** [vuetifyjs/vuetify-loader#89]
Copying in here my request from CLI plugin, too -

Please add the LICENSE file into the repository so that there are no legal questions to use the Vuetify Loader in commercial projects.

Thanks in advance!

**Comment by kinow** [comment]
Even though `package.json` has a license entry, it might be a good idea to also add a LICENSE file. Besides helping users that need to explain/answer to internal security groups about licenses, the GitHub interface will pick that up and make it available for users navigating/searching.
