### ISSUE TITLE
[Bug Report] Unknown custom element v-layout when using v-data-iterator

### ISSUE THREAD

**Issue by csheppard** [vuetifyjs/vuetify-loader#9]
### Versions and Environment
**Vuetify:** 1.3.0-alpha.1
**Vue:** 2.5.17
**Browsers:** Chrome 69.0.3497.100
**OS:** Mac OS 10.13.6

### Steps to reproduce
```
npm i
npm run dev
```

### Expected Behavior
Render the same example from https://vuetifyjs.com/en/components/data-iterator#usage--1 in `pages/index.vue`

### Actual Behavior
Chrome console errors:

```
commons.app.js:9035 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

[Vue warn]: Unknown custom element: <v-layout> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <VDataIterator>
       <VCard>
         <Pages/index.vue> at pages/index.vue
           <Nuxt>
             <VContent>
               <VApp>
                 <Default> at layouts/default.vue
                   <Root>

[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

[Vue warn]: Unknown custom element: <v-layout> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <VDataIterator>
       <VCard>
         <Pages/index.vue> at pages/index.vue
           <Nuxt>
             <VContent>
               <VApp>
                 <Default> at layouts/default.vue
                   <Root>
```

### Reproduction Link
[https://github.com/csheppard/nuxt-vuetify-loader](https://github.com/csheppard/nuxt-vuetify-loader)

### Other comments
This may not be related to Nuxt at all but its how I've encountered the error my app.

**Comment by KaelWD** [comment]
Dynamic components like that still have to be imported manually. In `plugins/vuetify.js`:
```js
import Vuetify, { VLayout } from 'vuetify/lib'

Vue.use(Vuetify, {
  components: {
    VLayout
  }
})
```

**Comment by javiertury** [comment]
I would like to clarify on @KaelWD solution. The component has also to be registered globally for this to work. It's useless to register the component on the module using `v-data-iterator`.

**Comment by KaelWD** [comment]
Documentation has been updated: https://vuetifyjs.com/en/guides/a-la-carte#loader-limitations

**Comment by ashikvs** [comment]
importing vlayout in vuetify as told by @KaelWD and using   <template slot="item" slot-scope="props"> solves the issue!

cheers!!
