### ISSUE TITLE
Loading images from inside a loop.

### ISSUE THREAD

**Issue by dschreij** [vuetifyjs/vuetify-loader#92]
According to the docs, it is possible to load images in a loop like this:

```vue
<v-img v-for="i in 10" :src="require(`@/images/image-${i}.jpg?vuetify-preload`)" :key="i">
```

However, this doesn't work in my case, as I get a build error that says the image cannot be located (i.e. Cannot find module '/img/services/instore.jpg'). I also get the warning:
```
Critical dependency: the request of a dependency is an expression
```
I dove into this, and I found this basically means webpack cannot 'require' modules at runtime, but only at build time. Since this require statement is dynamic (by using a template string) and is placed inside a loop, which is evaluated at runtime, it is difficult for webpack to handle this. The weird thing is that it does report my image path in the error message, so some evaluation must occur.

Is this reasoning correct, or am I doing something else wrong? Loading images with the progressive module works everywhere else, except for within a loop, so I know my setup is correct.

**Comment by KaelWD** [comment]
> According to the docs...

[citation needed]

You can load images in a loop, just not if it ends up requiring an expression as that cannot be determined at compile time.
