### ISSUE TITLE
[Bug Report] Slow build times when using Sass variables

### ISSUE THREAD

**Issue by mattgreenfield** [vuetifyjs/vuetify-loader#95]
### Environment

**Browsers:** Chrome 78.0.3904.87
**OS:** Mac OS 10.14.6

### Steps to reproduce
Create a vuetify project and override the Sass variables in either of these 2 ways:
1. Using "vue-cli-plugin-vuetify" and a `src/sass/variables.s(a|c)ss` file (that's auto imported)
2. Not using "vue-cli-plugin-vuetify", importing Sass variables in vue.config.js and using "'vuetify-loader/lib/plugin'"

As far as I'm aware these are the only 2 ways to set Sass variables?

A few weeks ago our build times were 20seconds (using vuetify 2.0.18) but they are now as much as 80~90seconds.

When the CLI estimates a percentage, it flies along pretty quick then it gets to 60% and keeps going up and down whilst it runs through the Vuetfiy components.

### Expected Behavior
Compile times similar to what they used to be

### Actual Behavior
Build times of 80~90seconds.

### Reproduction Link
<a href="" target="_blank"></a>

### Other comments
I've tried upgrading to "vue-cli-plugin-vuetify" version 2.0.0 and it didn't help.
It looks like a similar/same issue as this https://stackoverflow.com/questions/58441782/extremely-long-compile-times-with-vuetify-2-1-and-webpack

**Comment by KaelWD** [comment]
Vuetify-loader has nothing to do with sass, it just adds js imports for the components you use.

**Comment by mattgreenfield** [comment]
Ok, sorry to waste your time. I've raised a new issue on the Vuetify repo
