### ISSUE TITLE
[Bug Report] [Question] Issue about a-la-carte  

### ISSUE THREAD

**Issue by PhuHoaframgia** [vuetifyjs/vuetify-loader#98]
### Environment

**Browsers:** Chrome 78.0.3904.87
**OS:** Mac OS 10.14.6

### Steps to reproduce
this is my module:
![image](https://user-images.githubusercontent.com/23466462/68635734-0b081380-052c-11ea-9682-d060ee060265.png)

import in main.js
![image](https://user-images.githubusercontent.com/23466462/68635697-f297f900-052b-11ea-84f5-2ca34e87b452.png)

result is:
![image](https://user-images.githubusercontent.com/23466462/68635848-5ae6da80-052c-11ea-91e6-a70e30b2a2e2.png)

i follow a-la-carte  
i wonder that why it injects all components to the project?
how to fix it?

### Expected Behavior
Just inject the imported components

### Actual Behavior
a-la-carte  

### Reproduction Link
<a href="" target="_blank"></a>

**Comment by KaelWD** [comment]
Tree-shaking is only done in production mode.
