### ISSUE TITLE
[Bug Report] v-intersect raises exception if used with modifiers

### ISSUE THREAD

**Issue by Kritten** [vuetifyjs/vuetify-loader#99]
### Environment
**Vuetify Version:** 2.1.0
**Vue Version:** 2.6.10
**Browsers:** Chrome 78.0.3904.97
**OS:** Linux x86_64

### Steps to reproduce
Check out the repository, serve the app and open the console.

### Expected Behavior
The usage of the `v-intersect.quiet` directive in `src/App.vue` should not raise an exception.

### Actual Behavior
The directive raises `Failed to resolve directive: intersect` as if vue would not know the directive.
This also happens if one uses the `once` modifier.
BUT, everything works as expected if no modifier is used.

### Reproduction Link
<a href="https://github.com/Kritten/intersect-bug" target="_blank">https://github.com/Kritten/intersect-bug</a>

### Other comments
It is not reproduceable neither on codepen nor on codesandbox. 
Only in "real", local projects.

**Edit**
It works if one imports the directive directly in the component (many thanks to @jacekkarczmarczyk from discord ;))

**Comment by jacekkarczmarczyk** [comment]
Possible solution
```js
node.attrsList.forEach(({ name }) => attrs.add(name))
```

instead of 
```js
node.attrsList.forEach(({ name }) => attrs.add(name.replace(/^([^.:]+).*$/, '$1')))
```

in https://github.com/vuetifyjs/vuetify-loader/blob/master/lib/loader.js#L104

**Comment by jacekkarczmarczyk** [comment]
And workaround 

```js
const attrsMatch = (_, { kebabAttr, camelAttr }) => {
	console.log("test");
	if (!kebabAttr.startsWith('v-')) return

	const name = camelAttr.replace(/^V([^.:]+).*$/, '$1')
	const directory = kebabAttr.replace(/^v-([^.:]+).*$/, '$1')
	return [name, `import ${name} from 'vuetify/lib/directives/${directory}'`]
}

module.exports = {
	chainWebpack: config => {
		config.plugin('VuetifyLoaderPlugin').tap(args => [{ attrsMatch }])
	}
}
```

@Kritten

**Comment by MrXploder** [comment]
@jacekkarczmarczyk this workaround breaks others custom directives

These dependencies were not found:

* vuetify/lib/directives/grid-area in ./src/pages/dashboard.vue
* vuetify/lib/directives/model in ./src/components/DevicesDataTable.vue
* vuetify/lib/directives/on in ./src/pages/devices.vue

**Comment by jacekkarczmarczyk** [comment]
Right, you can check if the directive folder exists before returning `[data, ...`

**Comment by MrXploder** [comment]
not only that.... what happens with "v-model" and "v-on"? I have to import all Vue directives by myself?

**Comment by jacekkarczmarczyk** [comment]
`if the directive folder exists`
I meant in `node_modules/vuetify/...`, there is no `v-model` folder there
Or just wait until PR is merged

**Comment by MrXploder** [comment]
I'll wait, thank you very much.
